/**
 * Curated raw ingredient catalog — ~200 whole-food building blocks.
 *
 * Populated in Task 3 after Task 2's USDA fetch produces tmp/usda-raw.json.
 * Each entry must pass RawIngredientSchema (see ./schema.ts) or the build
 * script in Task 4 will fail.
 *
 * Priority tiers (ship order):
 *   P0 — ~73 must-ship items (globally top-tracked + Israeli staples)
 *   P1 — ~80 should-ship items (broader category coverage)
 *   P2 — ~60 nice-to-have items (prepared basics, edge condiments)
 *
 * Source comments per entry:
 *   // USDA SR Legacy <fdcId>      — values pulled from tmp/usda-raw.json
 *   // Tnuva label <month year>    — Tzameret-only items sourced from
 *                                    current manufacturer labels (no USDA
 *                                    match or Israeli-specific formulation)
 */

import type { RawIngredient } from './schema'

const g100 = { nameHe: '100 גרם', nameEn: '100g', unit: 'grams', grams: 100 }

const j = (sizes: { nameHe: string; nameEn: string; unit: string; grams: number }[]) =>
  JSON.stringify(sizes)

export const RAW_INGREDIENTS: RawIngredient[] = [
  // ─────────────────────────────────────────────────────────────────────
  // POULTRY (19) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_chicken_breast_raw',
    baseSlug: 'chicken_breast',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חזה עוף נא',
    nameEn: 'Chicken breast, raw',
    category: 'poultry',
    caloriesPer100g: 120,
    proteinPer100g: 22.5,
    fatPer100g: 2.62,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חזה בינוני', nameEn: 'Medium breast', unit: 'piece', grams: 170 },
      { nameHe: 'חזה גדול', nameEn: 'Large breast', unit: 'piece', grams: 300 },
    ]),
    sourceComment: 'USDA SR Legacy 171077',
  },
  {
    id: 'raw_chicken_breast_cooked',
    baseSlug: 'chicken_breast',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'חזה עוף צלוי',
    nameEn: 'Chicken breast, cooked',
    category: 'poultry',
    caloriesPer100g: 157,
    proteinPer100g: 32.06,
    fatPer100g: 3.24,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חזה בינוני (צלוי)', nameEn: 'Medium breast cooked', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 171140',
  },
  {
    id: 'raw_chicken_thigh_raw',
    baseSlug: 'chicken_thigh',
    state: 'raw',
    priority: 'P0',
    nameHe: 'ירך עוף נא',
    nameEn: 'Chicken thigh, raw',
    category: 'poultry',
    caloriesPer100g: 121,
    proteinPer100g: 19.66,
    fatPer100g: 4.12,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ירך בינונית', nameEn: 'Medium thigh', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 173627',
  },
  {
    id: 'raw_chicken_thigh_cooked',
    baseSlug: 'chicken_thigh',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'ירך עוף צלויה',
    nameEn: 'Chicken thigh, cooked',
    category: 'poultry',
    caloriesPer100g: 179,
    proteinPer100g: 24.76,
    fatPer100g: 8.15,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ירך בינונית (צלויה)', nameEn: 'Medium thigh cooked', unit: 'piece', grams: 110 },
    ]),
    sourceComment: 'USDA SR Legacy 172388',
  },
  {
    id: 'raw_chicken_drumstick_raw',
    baseSlug: 'chicken_drumstick',
    state: 'raw',
    priority: 'P1',
    nameHe: 'שוקיים עוף נא',
    nameEn: 'Chicken drumstick, raw',
    category: 'poultry',
    caloriesPer100g: 116,
    proteinPer100g: 19.41,
    fatPer100g: 3.71,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'שוק בינונית', nameEn: 'Medium drumstick', unit: 'piece', grams: 90 },
    ]),
    sourceComment: 'USDA SR Legacy 173614',
  },
  {
    id: 'raw_chicken_drumstick_cooked',
    baseSlug: 'chicken_drumstick',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'שוקיים עוף צלויות',
    nameEn: 'Chicken drumstick, cooked',
    category: 'poultry',
    caloriesPer100g: 155,
    proteinPer100g: 24.24,
    fatPer100g: 5.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      {
        nameHe: 'שוק בינונית (צלויה)',
        nameEn: 'Medium drumstick cooked',
        unit: 'piece',
        grams: 65,
      },
    ]),
    sourceComment: 'USDA SR Legacy 172376',
  },
  {
    id: 'raw_chicken_wing_raw',
    baseSlug: 'chicken_wing',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כנפי עוף נאות',
    nameEn: 'Chicken wing, raw',
    category: 'poultry',
    caloriesPer100g: 191,
    proteinPer100g: 17.52,
    fatPer100g: 12.85,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כנף אחת', nameEn: 'One wing', unit: 'piece', grams: 50 },
    ]),
    sourceComment: 'USDA SR Legacy 172390',
  },
  {
    id: 'raw_chicken_wing_cooked',
    baseSlug: 'chicken_wing',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'כנפי עוף צלויות',
    nameEn: 'Chicken wing, cooked',
    category: 'poultry',
    caloriesPer100g: 254,
    proteinPer100g: 23.79,
    fatPer100g: 16.87,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כנף אחת (צלויה)', nameEn: 'One wing cooked', unit: 'piece', grams: 35 },
    ]),
    sourceComment: 'USDA SR Legacy 173630',
  },
  {
    id: 'raw_chicken_whole_raw',
    baseSlug: 'chicken_whole',
    state: 'raw',
    priority: 'P1',
    nameHe: 'עוף שלם נא',
    nameEn: 'Chicken, whole, raw',
    category: 'poultry',
    caloriesPer100g: 215,
    proteinPer100g: 18.6,
    fatPer100g: 15.06,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'עוף שלם בינוני', nameEn: 'Medium whole chicken', unit: 'piece', grams: 1500 },
    ]),
    sourceComment: 'USDA SR Legacy 171447',
  },
  {
    id: 'raw_chicken_ground_raw',
    baseSlug: 'chicken_ground',
    state: 'raw',
    priority: 'P1',
    nameHe: 'בשר עוף טחון נא',
    nameEn: 'Chicken, ground, raw',
    category: 'poultry',
    caloriesPer100g: 143,
    proteinPer100g: 17.44,
    fatPer100g: 8.1,
    carbsPer100g: 0.04,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 171116',
  },
  {
    id: 'raw_chicken_ground_cooked',
    baseSlug: 'chicken_ground',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'בשר עוף טחון מבושל',
    nameEn: 'Chicken, ground, cooked',
    category: 'poultry',
    caloriesPer100g: 189,
    proteinPer100g: 23.28,
    fatPer100g: 10.92,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'קציצה', nameEn: 'Patty', unit: 'piece', grams: 85 }]),
    sourceComment: 'USDA SR Legacy 171117',
  },
  {
    id: 'raw_chicken_liver_raw',
    baseSlug: 'chicken_liver',
    state: 'raw',
    priority: 'P2',
    nameHe: 'כבד עוף נא',
    nameEn: 'Chicken liver, raw',
    category: 'poultry',
    caloriesPer100g: 119,
    proteinPer100g: 16.92,
    fatPer100g: 4.83,
    carbsPer100g: 0.73,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כבד אחד', nameEn: 'One liver', unit: 'piece', grams: 30 },
    ]),
    sourceComment: 'USDA SR Legacy 171060',
  },
  {
    id: 'raw_chicken_liver_cooked',
    baseSlug: 'chicken_liver',
    state: 'cooked',
    priority: 'P2',
    nameHe: 'כבד עוף מטוגן',
    nameEn: 'Chicken liver, cooked',
    category: 'poultry',
    caloriesPer100g: 172,
    proteinPer100g: 25.78,
    fatPer100g: 6.43,
    carbsPer100g: 1.11,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 85 }]),
    sourceComment: 'USDA SR Legacy 174491',
  },
  {
    id: 'raw_turkey_breast_raw',
    baseSlug: 'turkey_breast',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חזה הודו נא',
    nameEn: 'Turkey breast, raw',
    category: 'poultry',
    caloriesPer100g: 114,
    proteinPer100g: 23.66,
    fatPer100g: 1.48,
    carbsPer100g: 0.14,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 30 },
      { nameHe: 'סטייק', nameEn: 'Steak', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 171098',
  },
  {
    id: 'raw_turkey_breast_cooked',
    baseSlug: 'turkey_breast',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'חזה הודו צלוי',
    nameEn: 'Turkey breast, cooked',
    category: 'poultry',
    caloriesPer100g: 147,
    proteinPer100g: 30.13,
    fatPer100g: 2.08,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 30 }]),
    sourceComment: 'USDA SR Legacy 171496',
  },
  {
    id: 'raw_turkey_thigh_raw',
    baseSlug: 'turkey_thigh',
    state: 'raw',
    priority: 'P1',
    nameHe: 'ירך הודו נא',
    nameEn: 'Turkey thigh, raw',
    category: 'poultry',
    caloriesPer100g: 116,
    proteinPer100g: 20.6,
    fatPer100g: 3.69,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ירך בינונית', nameEn: 'Medium thigh', unit: 'piece', grams: 200 },
    ]),
    sourceComment: 'USDA SR Legacy 174518',
  },
  {
    id: 'raw_turkey_ground_93_raw',
    baseSlug: 'turkey_ground_93',
    state: 'raw',
    priority: 'P1',
    nameHe: 'בשר הודו טחון 7% שומן',
    nameEn: 'Turkey, ground, 93% lean, raw',
    category: 'poultry',
    caloriesPer100g: 150,
    proteinPer100g: 18.73,
    fatPer100g: 8.34,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 172850',
  },
  {
    id: 'raw_turkey_ground_93_cooked',
    baseSlug: 'turkey_ground_93',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'בשר הודו טחון 7% צלוי',
    nameEn: 'Turkey, ground, 93% lean, cooked',
    category: 'poultry',
    caloriesPer100g: 207,
    proteinPer100g: 25.86,
    fatPer100g: 11.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'קציצה', nameEn: 'Patty', unit: 'piece', grams: 85 }]),
    sourceComment: 'USDA SR Legacy 174492',
  },
  {
    id: 'raw_duck_breast_raw',
    baseSlug: 'duck_breast',
    state: 'raw',
    priority: 'P2',
    nameHe: 'חזה ברווז נא',
    nameEn: 'Duck breast, raw',
    category: 'poultry',
    caloriesPer100g: 123,
    proteinPer100g: 19.85,
    fatPer100g: 4.25,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חזה בינוני', nameEn: 'Medium breast', unit: 'piece', grams: 180 },
    ]),
    sourceComment: 'USDA SR Legacy 174469',
  },

  // ─────────────────────────────────────────────────────────────────────
  // EGGS (3) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_egg_whole_raw',
    baseSlug: 'egg_whole',
    state: 'raw',
    priority: 'P0',
    nameHe: 'ביצה שלמה',
    nameEn: 'Egg, whole, raw',
    category: 'eggs',
    caloriesPer100g: 143,
    proteinPer100g: 12.56,
    fatPer100g: 9.51,
    carbsPer100g: 0.72,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ביצה M', nameEn: 'Medium egg', unit: 'piece', grams: 50 },
      { nameHe: 'ביצה L', nameEn: 'Large egg', unit: 'piece', grams: 60 },
    ]),
    sourceComment: 'USDA SR Legacy 171287',
  },
  {
    id: 'raw_egg_white_raw',
    baseSlug: 'egg_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלבון ביצה',
    nameEn: 'Egg white, raw',
    category: 'eggs',
    caloriesPer100g: 52,
    proteinPer100g: 10.9,
    fatPer100g: 0.17,
    carbsPer100g: 0.73,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חלבון מביצה L', nameEn: 'White from large egg', unit: 'piece', grams: 33 },
    ]),
    sourceComment: 'USDA SR Legacy 172183',
  },
  {
    id: 'raw_egg_yolk_raw',
    baseSlug: 'egg_yolk',
    state: 'raw',
    priority: 'P1',
    nameHe: 'חלמון ביצה',
    nameEn: 'Egg yolk, raw',
    category: 'eggs',
    caloriesPer100g: 322,
    proteinPer100g: 15.86,
    fatPer100g: 26.54,
    carbsPer100g: 3.59,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חלמון מביצה L', nameEn: 'Yolk from large egg', unit: 'piece', grams: 17 },
    ]),
    sourceComment: 'USDA SR Legacy 172184',
  },

  // ─────────────────────────────────────────────────────────────────────
  // MEAT (18) — USDA SR Legacy (16) + Tzameret/label (2)
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_beef_ribeye_raw',
    baseSlug: 'beef_ribeye',
    state: 'raw',
    priority: 'P0',
    nameHe: 'אנטריקוט נא',
    nameEn: 'Beef ribeye, raw',
    category: 'meat',
    caloriesPer100g: 241,
    proteinPer100g: 18.69,
    fatPer100g: 18.43,
    carbsPer100g: 0.2,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני', nameEn: 'Medium steak', unit: 'piece', grams: 220 },
    ]),
    sourceComment: 'USDA SR Legacy 173403',
  },
  {
    id: 'raw_beef_ribeye_cooked',
    baseSlug: 'beef_ribeye',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'אנטריקוט צלוי',
    nameEn: 'Beef ribeye, cooked',
    category: 'meat',
    caloriesPer100g: 285,
    proteinPer100g: 23.89,
    fatPer100g: 21.1,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני (צלוי)', nameEn: 'Medium steak cooked', unit: 'piece', grams: 170 },
    ]),
    sourceComment: 'USDA SR Legacy 172165',
  },
  {
    id: 'raw_beef_sirloin_raw',
    baseSlug: 'beef_sirloin',
    state: 'raw',
    priority: 'P0',
    nameHe: 'סינטה נאה',
    nameEn: 'Beef sirloin, raw',
    category: 'meat',
    caloriesPer100g: 131,
    proteinPer100g: 22.09,
    fatPer100g: 4.08,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני', nameEn: 'Medium steak', unit: 'piece', grams: 200 },
    ]),
    sourceComment: 'USDA SR Legacy 174055',
  },
  {
    id: 'raw_beef_sirloin_cooked',
    baseSlug: 'beef_sirloin',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'סינטה צלויה',
    nameEn: 'Beef sirloin, cooked',
    category: 'meat',
    caloriesPer100g: 188,
    proteinPer100g: 30.29,
    fatPer100g: 6.55,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני (צלוי)', nameEn: 'Medium steak cooked', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 168635',
  },
  {
    id: 'raw_beef_brisket_raw',
    baseSlug: 'beef_brisket',
    state: 'raw',
    priority: 'P1',
    nameHe: 'חזה בקר נא',
    nameEn: 'Beef brisket, raw',
    category: 'meat',
    caloriesPer100g: 124,
    proteinPer100g: 21.74,
    fatPer100g: 4.14,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 168658',
  },
  {
    id: 'raw_beef_brisket_cooked',
    baseSlug: 'beef_brisket',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'חזה בקר מבושל',
    nameEn: 'Beef brisket, cooked',
    category: 'meat',
    caloriesPer100g: 221,
    proteinPer100g: 32.21,
    fatPer100g: 9.24,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 169440',
  },
  {
    id: 'raw_beef_ground_95_raw',
    baseSlug: 'beef_ground_95',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 5% שומן',
    nameEn: 'Beef, ground, 95% lean, raw',
    category: 'meat',
    caloriesPer100g: 137,
    proteinPer100g: 21.41,
    fatPer100g: 5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 171790',
  },
  {
    id: 'raw_beef_ground_95_cooked',
    baseSlug: 'beef_ground_95',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 5% צלוי',
    nameEn: 'Beef, ground, 95% lean, cooked',
    category: 'meat',
    caloriesPer100g: 164,
    proteinPer100g: 25.8,
    fatPer100g: 5.94,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'המבורגר', nameEn: 'Burger patty', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 171792',
  },
  {
    id: 'raw_beef_ground_80_raw',
    baseSlug: 'beef_ground_80',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 20% שומן',
    nameEn: 'Beef, ground, 80% lean, raw',
    category: 'meat',
    caloriesPer100g: 254,
    proteinPer100g: 17.17,
    fatPer100g: 20,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 174036',
  },
  {
    id: 'raw_beef_ground_80_cooked',
    baseSlug: 'beef_ground_80',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 20% צלוי',
    nameEn: 'Beef, ground, 80% lean, cooked',
    category: 'meat',
    caloriesPer100g: 246,
    proteinPer100g: 24.04,
    fatPer100g: 15.94,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'המבורגר', nameEn: 'Burger patty', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 171798',
  },
  {
    id: 'raw_beef_liver_raw',
    baseSlug: 'beef_liver',
    state: 'raw',
    priority: 'P2',
    nameHe: 'כבד בקר נא',
    nameEn: 'Beef liver, raw',
    category: 'meat',
    caloriesPer100g: 135,
    proteinPer100g: 20.36,
    fatPer100g: 3.63,
    carbsPer100g: 3.89,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 120 }]),
    sourceComment: 'USDA SR Legacy 169451',
  },
  {
    id: 'raw_beef_shoulder_raw',
    baseSlug: 'beef_shoulder',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כתף בקר נאה',
    nameEn: 'Beef shoulder, raw',
    category: 'meat',
    // Tzameret-only: not matched in USDA SR Legacy fetch. Values sourced from
    // Israeli butcher standard cut (Tnuva/Zogloveks reference, April 2026).
    caloriesPer100g: 180,
    proteinPer100g: 20.5,
    fatPer100g: 11,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'Tzameret / Israeli butcher reference, April 2026',
  },
  {
    id: 'raw_beef_shoulder_cooked',
    baseSlug: 'beef_shoulder',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'כתף בקר מבושלת',
    nameEn: 'Beef shoulder, cooked',
    category: 'meat',
    // Tzameret-only: braised shoulder, yield ~70% from raw.
    caloriesPer100g: 244,
    proteinPer100g: 27.5,
    fatPer100g: 14.5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 150 }]),
    sourceComment: 'Tzameret / Israeli butcher reference, April 2026',
  },
  {
    id: 'raw_lamb_shoulder_raw',
    baseSlug: 'lamb_shoulder',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כתף כבש נאה',
    nameEn: 'Lamb shoulder, raw',
    category: 'meat',
    caloriesPer100g: 272,
    proteinPer100g: 16.16,
    fatPer100g: 22.89,
    carbsPer100g: 0.24,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 175262',
  },
  {
    id: 'raw_lamb_shoulder_cooked',
    baseSlug: 'lamb_shoulder',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'כתף כבש מבושלת',
    nameEn: 'Lamb shoulder, cooked',
    category: 'meat',
    caloriesPer100g: 285,
    proteinPer100g: 34.06,
    fatPer100g: 15.5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 173814',
  },
  {
    id: 'raw_lamb_leg_raw',
    baseSlug: 'lamb_leg',
    state: 'raw',
    priority: 'P1',
    nameHe: 'ירך כבש נאה',
    nameEn: 'Lamb leg, raw',
    category: 'meat',
    caloriesPer100g: 206,
    proteinPer100g: 18.64,
    fatPer100g: 14.52,
    carbsPer100g: 0.13,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 174342',
  },
  {
    id: 'raw_lamb_ground_raw',
    baseSlug: 'lamb_ground',
    state: 'raw',
    priority: 'P2',
    nameHe: 'בשר כבש טחון נא',
    nameEn: 'Lamb, ground, raw',
    category: 'meat',
    caloriesPer100g: 282,
    proteinPer100g: 16.56,
    fatPer100g: 23.41,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 174370',
  },
  {
    id: 'raw_veal_cutlet_raw',
    baseSlug: 'veal_cutlet',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שניצל עגל נא',
    nameEn: 'Veal cutlet, raw',
    category: 'meat',
    caloriesPer100g: 117,
    proteinPer100g: 20.98,
    fatPer100g: 3.08,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Cutlet', unit: 'piece', grams: 100 }]),
    sourceComment: 'USDA SR Legacy 175268',
  },

  // ─────────────────────────────────────────────────────────────────────
  // FISH (13) — USDA SR Legacy (12) + Tzameret/label (1)
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_salmon_atlantic_raw',
    baseSlug: 'salmon_atlantic',
    state: 'raw',
    priority: 'P0',
    nameHe: 'סלמון נא',
    nameEn: 'Salmon, Atlantic, raw',
    category: 'fish',
    caloriesPer100g: 208,
    proteinPer100g: 20.42,
    fatPer100g: 13.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
      { nameHe: 'פילה גדול', nameEn: 'Large fillet', unit: 'piece', grams: 220 },
    ]),
    sourceComment: 'USDA SR Legacy 175167',
  },
  {
    id: 'raw_salmon_atlantic_cooked',
    baseSlug: 'salmon_atlantic',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'סלמון צלוי',
    nameEn: 'Salmon, Atlantic, cooked',
    category: 'fish',
    caloriesPer100g: 206,
    proteinPer100g: 22.1,
    fatPer100g: 12.35,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני (צלוי)', nameEn: 'Medium fillet cooked', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 175168',
  },
  {
    id: 'raw_tuna_yellowfin_raw',
    baseSlug: 'tuna_yellowfin',
    state: 'raw',
    priority: 'P0',
    nameHe: 'טונה צהובת סנפיר טריה',
    nameEn: 'Tuna, yellowfin, raw',
    category: 'fish',
    caloriesPer100g: 109,
    proteinPer100g: 24.4,
    fatPer100g: 0.49,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'סטייק', nameEn: 'Steak', unit: 'piece', grams: 170 }]),
    sourceComment: 'USDA SR Legacy 175159',
  },
  {
    id: 'raw_tuna_canned_water_raw',
    baseSlug: 'tuna_canned_water',
    state: 'raw',
    priority: 'P0',
    nameHe: 'טונה בשימורים במים',
    nameEn: 'Tuna, canned in water, drained',
    category: 'fish',
    caloriesPer100g: 116,
    proteinPer100g: 25.51,
    fatPer100g: 0.82,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קופסה קטנה (מסונן)', nameEn: 'Small can (drained)', unit: 'piece', grams: 120 },
      { nameHe: 'קופסה גדולה (מסונן)', nameEn: 'Large can (drained)', unit: 'piece', grams: 160 },
    ]),
    sourceComment: 'USDA SR Legacy 171986',
  },
  {
    id: 'raw_tilapia_raw',
    baseSlug: 'tilapia',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אמנון (טילפיה) נא',
    nameEn: 'Tilapia, raw',
    category: 'fish',
    caloriesPer100g: 96,
    proteinPer100g: 20.08,
    fatPer100g: 1.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 175176',
  },
  {
    id: 'raw_tilapia_cooked',
    baseSlug: 'tilapia',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'אמנון (טילפיה) צלוי',
    nameEn: 'Tilapia, cooked',
    category: 'fish',
    caloriesPer100g: 128,
    proteinPer100g: 26.15,
    fatPer100g: 2.65,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני (צלוי)', nameEn: 'Medium fillet cooked', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 175177',
  },
  {
    id: 'raw_sardine_canned_oil_raw',
    baseSlug: 'sardine_canned_oil',
    state: 'raw',
    priority: 'P1',
    nameHe: 'סרדינים בשמן',
    nameEn: 'Sardine, canned in oil, drained',
    category: 'fish',
    caloriesPer100g: 208,
    proteinPer100g: 24.62,
    fatPer100g: 11.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קופסה', nameEn: 'Can (drained)', unit: 'piece', grams: 90 },
    ]),
    sourceComment: 'USDA SR Legacy 175139',
  },
  {
    id: 'raw_mackerel_raw',
    baseSlug: 'mackerel',
    state: 'raw',
    priority: 'P2',
    nameHe: 'מקרל נא',
    nameEn: 'Mackerel, raw',
    category: 'fish',
    caloriesPer100g: 205,
    proteinPer100g: 18.6,
    fatPer100g: 13.89,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 175119',
  },
  {
    id: 'raw_cod_raw',
    baseSlug: 'cod',
    state: 'raw',
    priority: 'P2',
    nameHe: 'בקלה נא',
    nameEn: 'Cod, raw',
    category: 'fish',
    caloriesPer100g: 82,
    proteinPer100g: 17.81,
    fatPer100g: 0.67,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 171955',
  },
  {
    id: 'raw_shrimp_raw',
    baseSlug: 'shrimp',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שרימפס נאים',
    nameEn: 'Shrimp, raw',
    category: 'fish',
    caloriesPer100g: 85,
    proteinPer100g: 20.1,
    fatPer100g: 0.51,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'שרימפ בודד', nameEn: 'Single shrimp', unit: 'piece', grams: 7 },
    ]),
    sourceComment: 'USDA SR Legacy 175179',
  },
  {
    id: 'raw_trout_raw',
    baseSlug: 'trout',
    state: 'raw',
    priority: 'P2',
    nameHe: 'פורל נא',
    nameEn: 'Trout, rainbow, raw',
    category: 'fish',
    caloriesPer100g: 141,
    proteinPer100g: 19.94,
    fatPer100g: 6.18,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 173717',
  },
  {
    id: 'raw_salmon_smoked_raw',
    baseSlug: 'salmon_smoked',
    state: 'raw',
    priority: 'P1',
    nameHe: 'סלמון מעושן',
    nameEn: 'Salmon, smoked',
    category: 'fish',
    caloriesPer100g: 117,
    proteinPer100g: 18.28,
    fatPer100g: 4.32,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 15 },
      { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 100 },
    ]),
    sourceComment: 'USDA SR Legacy 173687',
  },
  {
    id: 'raw_sea_bream_raw',
    baseSlug: 'sea_bream',
    state: 'raw',
    priority: 'P1',
    nameHe: 'דניס נא',
    nameEn: 'Sea bream (denis), raw',
    category: 'fish',
    // Tzameret-only: common Israeli lean white fish; USDA has no direct match.
    // Values from published lean white fish profile (gilthead sea bream).
    caloriesPer100g: 135,
    proteinPer100g: 19.8,
    fatPer100g: 6,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'דג שלם בינוני', nameEn: 'Medium whole fish', unit: 'piece', grams: 350 },
      { nameHe: 'פילה', nameEn: 'Fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'Tzameret / Israeli fishmonger reference, April 2026',
  },

  // ─────────────────────────────────────────────────────────────────────
  // DAIRY (18) — USDA SR Legacy (11) + Tzameret/label (7)
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_milk_1pct_raw',
    baseSlug: 'milk_1pct',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלב 1%',
    nameEn: 'Milk, 1%',
    category: 'dairy',
    caloriesPer100g: 42,
    proteinPer100g: 3.37,
    fatPer100g: 0.97,
    carbsPer100g: 4.99,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'piece', grams: 240 }]),
    sourceComment: 'USDA SR Legacy 170872',
  },
  {
    id: 'raw_milk_whole_raw',
    baseSlug: 'milk_whole',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלב 3.25%',
    nameEn: 'Milk, whole (3.25%)',
    category: 'dairy',
    caloriesPer100g: 61,
    proteinPer100g: 3.15,
    fatPer100g: 3.25,
    carbsPer100g: 4.8,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'piece', grams: 240 }]),
    sourceComment: 'USDA SR Legacy 171265',
  },
  {
    id: 'raw_milk_3pct_raw',
    baseSlug: 'milk_3pct',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלב 3%',
    nameEn: 'Milk, 3% (Israeli standard)',
    category: 'dairy',
    // Tzameret-only: Israeli standard 3% milk (Tnuva/Tara label, April 2026).
    caloriesPer100g: 62,
    proteinPer100g: 3.3,
    fatPer100g: 3,
    carbsPer100g: 4.7,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'piece', grams: 240 }]),
    sourceComment: 'Tnuva/Tara label April 2026',
  },
  {
    id: 'raw_yogurt_plain_lowfat_raw',
    baseSlug: 'yogurt_plain_lowfat',
    state: 'raw',
    priority: 'P0',
    nameHe: 'יוגורט טבעי דל שומן',
    nameEn: 'Yogurt, plain, low fat',
    category: 'dairy',
    caloriesPer100g: 63,
    proteinPer100g: 5.25,
    fatPer100g: 1.55,
    carbsPer100g: 7.04,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 170886',
  },
  {
    id: 'raw_yogurt_plain_whole_raw',
    baseSlug: 'yogurt_plain_whole',
    state: 'raw',
    priority: 'P1',
    nameHe: 'יוגורט טבעי מלא',
    nameEn: 'Yogurt, plain, whole milk',
    category: 'dairy',
    caloriesPer100g: 61,
    proteinPer100g: 3.47,
    fatPer100g: 3.25,
    carbsPer100g: 4.66,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 171284',
  },
  {
    id: 'raw_yogurt_greek_nonfat_raw',
    baseSlug: 'yogurt_greek_nonfat',
    state: 'raw',
    priority: 'P0',
    nameHe: 'יוגורט יווני 0%',
    nameEn: 'Yogurt, Greek, nonfat',
    category: 'dairy',
    caloriesPer100g: 54,
    proteinPer100g: 9.53,
    fatPer100g: 0.24,
    carbsPer100g: 3.43,
    fiberPer100g: 0.2,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 170 }]),
    sourceComment: 'USDA SR Legacy 171312',
  },
  {
    id: 'raw_yogurt_greek_whole_raw',
    baseSlug: 'yogurt_greek_whole',
    state: 'raw',
    priority: 'P1',
    nameHe: 'יוגורט יווני מלא',
    nameEn: 'Yogurt, Greek, whole milk',
    category: 'dairy',
    caloriesPer100g: 97,
    proteinPer100g: 9,
    fatPer100g: 5,
    carbsPer100g: 3.98,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 170 }]),
    sourceComment: 'USDA SR Legacy 171304',
  },
  {
    id: 'raw_feta_raw',
    baseSlug: 'feta',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת פטה',
    nameEn: 'Feta cheese',
    category: 'dairy',
    caloriesPer100g: 265,
    proteinPer100g: 14.21,
    fatPer100g: 21.49,
    carbsPer100g: 3.88,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'קובייה', nameEn: 'Cube', unit: 'piece', grams: 30 }]),
    sourceComment: 'USDA SR Legacy 173420',
  },
  {
    id: 'raw_mozzarella_raw',
    baseSlug: 'mozzarella',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת מוצרלה',
    nameEn: 'Mozzarella, part-skim',
    category: 'dairy',
    caloriesPer100g: 295,
    proteinPer100g: 23.75,
    fatPer100g: 19.78,
    carbsPer100g: 5.58,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 171244',
  },
  {
    id: 'raw_butter_raw',
    baseSlug: 'butter',
    state: 'raw',
    priority: 'P1',
    nameHe: 'חמאה',
    nameEn: 'Butter, unsalted',
    category: 'dairy',
    caloriesPer100g: 717,
    proteinPer100g: 0.85,
    fatPer100g: 81.11,
    carbsPer100g: 0.06,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 5 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 14 },
    ]),
    sourceComment: 'USDA SR Legacy 173430',
  },
  {
    id: 'raw_cream_cheese_full_raw',
    baseSlug: 'cream_cheese_full',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת שמנת (מלאה)',
    nameEn: 'Cream cheese',
    category: 'dairy',
    caloriesPer100g: 350,
    proteinPer100g: 6.15,
    fatPer100g: 34.44,
    carbsPer100g: 5.52,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף למריחה', nameEn: 'Spread tbsp', unit: 'tbsp', grams: 15 },
    ]),
    sourceComment: 'USDA SR Legacy 173418',
  },
  {
    id: 'raw_sour_cream_raw',
    baseSlug: 'sour_cream',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שמנת חמוצה',
    nameEn: 'Sour cream',
    category: 'dairy',
    caloriesPer100g: 198,
    proteinPer100g: 2.44,
    fatPer100g: 19.35,
    carbsPer100g: 4.63,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 12 }]),
    sourceComment: 'USDA SR Legacy 171257',
  },
  {
    id: 'raw_labneh_raw',
    baseSlug: 'labneh',
    state: 'raw',
    priority: 'P0',
    nameHe: 'לבנה 5%',
    nameEn: 'Labneh 5%',
    category: 'dairy',
    // Tzameret-only: Tnuva/Piraeus labneh 5% label (April 2026).
    caloriesPer100g: 112,
    proteinPer100g: 7,
    fatPer100g: 5,
    carbsPer100g: 4,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 200 }]),
    sourceComment: 'Tnuva labneh 5% label, April 2026',
  },
  {
    id: 'raw_white_cheese_5_raw',
    baseSlug: 'white_cheese_5',
    state: 'raw',
    priority: 'P0',
    nameHe: 'גבינה לבנה 5%',
    nameEn: 'White cheese 5% (gvina levana)',
    category: 'dairy',
    // Tzameret-only: Tnuva gvina levana 5% label (April 2026).
    caloriesPer100g: 100,
    proteinPer100g: 11,
    fatPer100g: 5,
    carbsPer100g: 3,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 250 }]),
    sourceComment: 'Tnuva white cheese 5% label, April 2026',
  },
  {
    id: 'raw_cottage_5_raw',
    baseSlug: 'cottage_5',
    state: 'raw',
    priority: 'P0',
    nameHe: "קוטג' 5%",
    nameEn: 'Cottage cheese 5%',
    category: 'dairy',
    // Tzameret-only: Tnuva cottage 5% label (April 2026).
    caloriesPer100g: 100,
    proteinPer100g: 11,
    fatPer100g: 5,
    carbsPer100g: 3,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 250 }]),
    sourceComment: 'Tnuva cottage 5% label, April 2026',
  },
  {
    id: 'raw_cottage_9_raw',
    baseSlug: 'cottage_9',
    state: 'raw',
    priority: 'P1',
    nameHe: "קוטג' 9%",
    nameEn: 'Cottage cheese 9%',
    category: 'dairy',
    // Tzameret-only: Tnuva cottage 9% label (April 2026).
    caloriesPer100g: 135,
    proteinPer100g: 11,
    fatPer100g: 9,
    carbsPer100g: 3,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 250 }]),
    sourceComment: 'Tnuva cottage 9% label, April 2026',
  },
  {
    id: 'raw_emek_raw',
    baseSlug: 'emek',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת עמק',
    nameEn: 'Emek cheese',
    category: 'dairy',
    // Tzameret-only: Tnuva Emek yellow cheese label (April 2026).
    caloriesPer100g: 332,
    proteinPer100g: 25,
    fatPer100g: 25,
    carbsPer100g: 2,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 25 }]),
    sourceComment: 'Tnuva Emek label, April 2026',
  },
]
