/**
 * Curated raw ingredient catalog — ~200 whole-food building blocks.
 *
 * Populated in Task 3 after Task 2's USDA fetch produces tmp/usda-raw.json.
 * Each entry must pass RawIngredientSchema (see ./schema.ts) or the build
 * script in Task 4 will fail.
 *
 * Priority tiers (ship order):
 *   P0 — ~73 must-ship items (globally top-tracked + Israeli staples)
 *   P1 — ~80 should-ship items (broader category coverage)
 *   P2 — ~60 nice-to-have items (prepared basics, edge condiments)
 *
 * Source comments per entry:
 *   // USDA SR Legacy <fdcId>      — values pulled from tmp/usda-raw.json
 *   // Tnuva label <month year>    — Tzameret-only items sourced from
 *                                    current manufacturer labels (no USDA
 *                                    match or Israeli-specific formulation)
 */

import type { RawIngredient } from './schema'

const g100 = { nameHe: '100 גרם', nameEn: '100g', unit: 'grams', grams: 100 }

const j = (sizes: { nameHe: string; nameEn: string; unit: string; grams: number }[]) =>
  JSON.stringify(sizes)

export const RAW_INGREDIENTS: RawIngredient[] = [
  // ─────────────────────────────────────────────────────────────────────
  // POULTRY (19) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_chicken_breast_raw',
    baseSlug: 'chicken_breast',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חזה עוף נא',
    nameEn: 'Chicken breast, raw',
    category: 'poultry',
    caloriesPer100g: 120,
    proteinPer100g: 22.5,
    fatPer100g: 2.62,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חזה בינוני', nameEn: 'Medium breast', unit: 'piece', grams: 170 },
      { nameHe: 'חזה גדול', nameEn: 'Large breast', unit: 'piece', grams: 300 },
    ]),
    sourceComment: 'USDA SR Legacy 171077',
  },
  {
    id: 'raw_chicken_breast_cooked',
    baseSlug: 'chicken_breast',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'חזה עוף צלוי',
    nameEn: 'Chicken breast, cooked',
    category: 'poultry',
    caloriesPer100g: 157,
    proteinPer100g: 32.06,
    fatPer100g: 3.24,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חזה בינוני (צלוי)', nameEn: 'Medium breast cooked', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 171140',
  },
  {
    id: 'raw_chicken_thigh_raw',
    baseSlug: 'chicken_thigh',
    state: 'raw',
    priority: 'P0',
    nameHe: 'ירך עוף נא',
    nameEn: 'Chicken thigh, raw',
    category: 'poultry',
    caloriesPer100g: 121,
    proteinPer100g: 19.66,
    fatPer100g: 4.12,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ירך בינונית', nameEn: 'Medium thigh', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 173627',
  },
  {
    id: 'raw_chicken_thigh_cooked',
    baseSlug: 'chicken_thigh',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'ירך עוף צלויה',
    nameEn: 'Chicken thigh, cooked',
    category: 'poultry',
    caloriesPer100g: 179,
    proteinPer100g: 24.76,
    fatPer100g: 8.15,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ירך בינונית (צלויה)', nameEn: 'Medium thigh cooked', unit: 'piece', grams: 110 },
    ]),
    sourceComment: 'USDA SR Legacy 172388',
  },
  {
    id: 'raw_chicken_drumstick_raw',
    baseSlug: 'chicken_drumstick',
    state: 'raw',
    priority: 'P1',
    nameHe: 'שוקיים עוף נא',
    nameEn: 'Chicken drumstick, raw',
    category: 'poultry',
    caloriesPer100g: 116,
    proteinPer100g: 19.41,
    fatPer100g: 3.71,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'שוק בינונית', nameEn: 'Medium drumstick', unit: 'piece', grams: 90 },
    ]),
    sourceComment: 'USDA SR Legacy 173614',
  },
  {
    id: 'raw_chicken_drumstick_cooked',
    baseSlug: 'chicken_drumstick',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'שוקיים עוף צלויות',
    nameEn: 'Chicken drumstick, cooked',
    category: 'poultry',
    caloriesPer100g: 155,
    proteinPer100g: 24.24,
    fatPer100g: 5.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      {
        nameHe: 'שוק בינונית (צלויה)',
        nameEn: 'Medium drumstick cooked',
        unit: 'piece',
        grams: 65,
      },
    ]),
    sourceComment: 'USDA SR Legacy 172376',
  },
  {
    id: 'raw_chicken_wing_raw',
    baseSlug: 'chicken_wing',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כנפי עוף נאות',
    nameEn: 'Chicken wing, raw',
    category: 'poultry',
    caloriesPer100g: 191,
    proteinPer100g: 17.52,
    fatPer100g: 12.85,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כנף אחת', nameEn: 'One wing', unit: 'piece', grams: 50 },
    ]),
    sourceComment: 'USDA SR Legacy 172390',
  },
  {
    id: 'raw_chicken_wing_cooked',
    baseSlug: 'chicken_wing',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'כנפי עוף צלויות',
    nameEn: 'Chicken wing, cooked',
    category: 'poultry',
    caloriesPer100g: 254,
    proteinPer100g: 23.79,
    fatPer100g: 16.87,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כנף אחת (צלויה)', nameEn: 'One wing cooked', unit: 'piece', grams: 35 },
    ]),
    sourceComment: 'USDA SR Legacy 173630',
  },
  {
    id: 'raw_chicken_whole_raw',
    baseSlug: 'chicken_whole',
    state: 'raw',
    priority: 'P1',
    nameHe: 'עוף שלם נא',
    nameEn: 'Chicken, whole, raw',
    category: 'poultry',
    caloriesPer100g: 215,
    proteinPer100g: 18.6,
    fatPer100g: 15.06,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'עוף שלם בינוני', nameEn: 'Medium whole chicken', unit: 'piece', grams: 1500 },
    ]),
    sourceComment: 'USDA SR Legacy 171447',
  },
  {
    id: 'raw_chicken_ground_raw',
    baseSlug: 'chicken_ground',
    state: 'raw',
    priority: 'P1',
    nameHe: 'בשר עוף טחון נא',
    nameEn: 'Chicken, ground, raw',
    category: 'poultry',
    caloriesPer100g: 143,
    proteinPer100g: 17.44,
    fatPer100g: 8.1,
    carbsPer100g: 0.04,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 171116',
  },
  {
    id: 'raw_chicken_ground_cooked',
    baseSlug: 'chicken_ground',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'בשר עוף טחון מבושל',
    nameEn: 'Chicken, ground, cooked',
    category: 'poultry',
    caloriesPer100g: 189,
    proteinPer100g: 23.28,
    fatPer100g: 10.92,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'קציצה', nameEn: 'Patty', unit: 'piece', grams: 85 }]),
    sourceComment: 'USDA SR Legacy 171117',
  },
  {
    id: 'raw_chicken_liver_raw',
    baseSlug: 'chicken_liver',
    state: 'raw',
    priority: 'P2',
    nameHe: 'כבד עוף נא',
    nameEn: 'Chicken liver, raw',
    category: 'poultry',
    caloriesPer100g: 119,
    proteinPer100g: 16.92,
    fatPer100g: 4.83,
    carbsPer100g: 0.73,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כבד אחד', nameEn: 'One liver', unit: 'piece', grams: 30 },
    ]),
    sourceComment: 'USDA SR Legacy 171060',
  },
  {
    id: 'raw_chicken_liver_cooked',
    baseSlug: 'chicken_liver',
    state: 'cooked',
    priority: 'P2',
    nameHe: 'כבד עוף מטוגן',
    nameEn: 'Chicken liver, cooked',
    category: 'poultry',
    caloriesPer100g: 172,
    proteinPer100g: 25.78,
    fatPer100g: 6.43,
    carbsPer100g: 1.11,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 85 }]),
    sourceComment: 'USDA SR Legacy 174491',
  },
  {
    id: 'raw_turkey_breast_raw',
    baseSlug: 'turkey_breast',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חזה הודו נא',
    nameEn: 'Turkey breast, raw',
    category: 'poultry',
    caloriesPer100g: 114,
    proteinPer100g: 23.66,
    fatPer100g: 1.48,
    carbsPer100g: 0.14,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 30 },
      { nameHe: 'סטייק', nameEn: 'Steak', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 171098',
  },
  {
    id: 'raw_turkey_breast_cooked',
    baseSlug: 'turkey_breast',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'חזה הודו צלוי',
    nameEn: 'Turkey breast, cooked',
    category: 'poultry',
    caloriesPer100g: 147,
    proteinPer100g: 30.13,
    fatPer100g: 2.08,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 30 }]),
    sourceComment: 'USDA SR Legacy 171496',
  },
  {
    id: 'raw_turkey_thigh_raw',
    baseSlug: 'turkey_thigh',
    state: 'raw',
    priority: 'P1',
    nameHe: 'ירך הודו נא',
    nameEn: 'Turkey thigh, raw',
    category: 'poultry',
    caloriesPer100g: 116,
    proteinPer100g: 20.6,
    fatPer100g: 3.69,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ירך בינונית', nameEn: 'Medium thigh', unit: 'piece', grams: 200 },
    ]),
    sourceComment: 'USDA SR Legacy 174518',
  },
  {
    id: 'raw_turkey_ground_93_raw',
    baseSlug: 'turkey_ground_93',
    state: 'raw',
    priority: 'P1',
    nameHe: 'בשר הודו טחון 7% שומן',
    nameEn: 'Turkey, ground, 93% lean, raw',
    category: 'poultry',
    caloriesPer100g: 150,
    proteinPer100g: 18.73,
    fatPer100g: 8.34,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 172850',
  },
  {
    id: 'raw_turkey_ground_93_cooked',
    baseSlug: 'turkey_ground_93',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'בשר הודו טחון 7% צלוי',
    nameEn: 'Turkey, ground, 93% lean, cooked',
    category: 'poultry',
    caloriesPer100g: 207,
    proteinPer100g: 25.86,
    fatPer100g: 11.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'קציצה', nameEn: 'Patty', unit: 'piece', grams: 85 }]),
    sourceComment: 'USDA SR Legacy 174492',
  },
  {
    id: 'raw_duck_breast_raw',
    baseSlug: 'duck_breast',
    state: 'raw',
    priority: 'P2',
    nameHe: 'חזה ברווז נא',
    nameEn: 'Duck breast, raw',
    category: 'poultry',
    caloriesPer100g: 123,
    proteinPer100g: 19.85,
    fatPer100g: 4.25,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חזה בינוני', nameEn: 'Medium breast', unit: 'piece', grams: 180 },
    ]),
    sourceComment: 'USDA SR Legacy 174469',
  },

  // ─────────────────────────────────────────────────────────────────────
  // EGGS (3) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_egg_whole_raw',
    baseSlug: 'egg_whole',
    state: 'raw',
    priority: 'P0',
    nameHe: 'ביצה שלמה',
    nameEn: 'Egg, whole, raw',
    category: 'eggs',
    caloriesPer100g: 143,
    proteinPer100g: 12.56,
    fatPer100g: 9.51,
    carbsPer100g: 0.72,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'ביצה M', nameEn: 'Medium egg', unit: 'piece', grams: 50 },
      { nameHe: 'ביצה L', nameEn: 'Large egg', unit: 'piece', grams: 60 },
    ]),
    sourceComment: 'USDA SR Legacy 171287',
  },
  {
    id: 'raw_egg_white_raw',
    baseSlug: 'egg_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלבון ביצה',
    nameEn: 'Egg white, raw',
    category: 'eggs',
    caloriesPer100g: 52,
    proteinPer100g: 10.9,
    fatPer100g: 0.17,
    carbsPer100g: 0.73,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חלבון מביצה L', nameEn: 'White from large egg', unit: 'piece', grams: 33 },
    ]),
    sourceComment: 'USDA SR Legacy 172183',
  },
  {
    id: 'raw_egg_yolk_raw',
    baseSlug: 'egg_yolk',
    state: 'raw',
    priority: 'P1',
    nameHe: 'חלמון ביצה',
    nameEn: 'Egg yolk, raw',
    category: 'eggs',
    caloriesPer100g: 322,
    proteinPer100g: 15.86,
    fatPer100g: 26.54,
    carbsPer100g: 3.59,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חלמון מביצה L', nameEn: 'Yolk from large egg', unit: 'piece', grams: 17 },
    ]),
    sourceComment: 'USDA SR Legacy 172184',
  },

  // ─────────────────────────────────────────────────────────────────────
  // MEAT (18) — USDA SR Legacy (16) + Tzameret/label (2)
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_beef_ribeye_raw',
    baseSlug: 'beef_ribeye',
    state: 'raw',
    priority: 'P0',
    nameHe: 'אנטריקוט נא',
    nameEn: 'Beef ribeye, raw',
    category: 'meat',
    caloriesPer100g: 241,
    proteinPer100g: 18.69,
    fatPer100g: 18.43,
    carbsPer100g: 0.2,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני', nameEn: 'Medium steak', unit: 'piece', grams: 220 },
    ]),
    sourceComment: 'USDA SR Legacy 173403',
  },
  {
    id: 'raw_beef_ribeye_cooked',
    baseSlug: 'beef_ribeye',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'אנטריקוט צלוי',
    nameEn: 'Beef ribeye, cooked',
    category: 'meat',
    caloriesPer100g: 285,
    proteinPer100g: 23.89,
    fatPer100g: 21.1,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני (צלוי)', nameEn: 'Medium steak cooked', unit: 'piece', grams: 170 },
    ]),
    sourceComment: 'USDA SR Legacy 172165',
  },
  {
    id: 'raw_beef_sirloin_raw',
    baseSlug: 'beef_sirloin',
    state: 'raw',
    priority: 'P0',
    nameHe: 'סינטה נאה',
    nameEn: 'Beef sirloin, raw',
    category: 'meat',
    caloriesPer100g: 131,
    proteinPer100g: 22.09,
    fatPer100g: 4.08,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני', nameEn: 'Medium steak', unit: 'piece', grams: 200 },
    ]),
    sourceComment: 'USDA SR Legacy 174055',
  },
  {
    id: 'raw_beef_sirloin_cooked',
    baseSlug: 'beef_sirloin',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'סינטה צלויה',
    nameEn: 'Beef sirloin, cooked',
    category: 'meat',
    caloriesPer100g: 188,
    proteinPer100g: 30.29,
    fatPer100g: 6.55,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סטייק בינוני (צלוי)', nameEn: 'Medium steak cooked', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 168635',
  },
  {
    id: 'raw_beef_brisket_raw',
    baseSlug: 'beef_brisket',
    state: 'raw',
    priority: 'P1',
    nameHe: 'חזה בקר נא',
    nameEn: 'Beef brisket, raw',
    category: 'meat',
    caloriesPer100g: 124,
    proteinPer100g: 21.74,
    fatPer100g: 4.14,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 168658',
  },
  {
    id: 'raw_beef_brisket_cooked',
    baseSlug: 'beef_brisket',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'חזה בקר מבושל',
    nameEn: 'Beef brisket, cooked',
    category: 'meat',
    caloriesPer100g: 221,
    proteinPer100g: 32.21,
    fatPer100g: 9.24,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 169440',
  },
  {
    id: 'raw_beef_ground_95_raw',
    baseSlug: 'beef_ground_95',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 5% שומן',
    nameEn: 'Beef, ground, 95% lean, raw',
    category: 'meat',
    caloriesPer100g: 137,
    proteinPer100g: 21.41,
    fatPer100g: 5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 171790',
  },
  {
    id: 'raw_beef_ground_95_cooked',
    baseSlug: 'beef_ground_95',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 5% צלוי',
    nameEn: 'Beef, ground, 95% lean, cooked',
    category: 'meat',
    caloriesPer100g: 164,
    proteinPer100g: 25.8,
    fatPer100g: 5.94,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'המבורגר', nameEn: 'Burger patty', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 171792',
  },
  {
    id: 'raw_beef_ground_80_raw',
    baseSlug: 'beef_ground_80',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 20% שומן',
    nameEn: 'Beef, ground, 80% lean, raw',
    category: 'meat',
    caloriesPer100g: 254,
    proteinPer100g: 17.17,
    fatPer100g: 20,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 174036',
  },
  {
    id: 'raw_beef_ground_80_cooked',
    baseSlug: 'beef_ground_80',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'בשר בקר טחון 20% צלוי',
    nameEn: 'Beef, ground, 80% lean, cooked',
    category: 'meat',
    caloriesPer100g: 246,
    proteinPer100g: 24.04,
    fatPer100g: 15.94,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'המבורגר', nameEn: 'Burger patty', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 171798',
  },
  {
    id: 'raw_beef_liver_raw',
    baseSlug: 'beef_liver',
    state: 'raw',
    priority: 'P2',
    nameHe: 'כבד בקר נא',
    nameEn: 'Beef liver, raw',
    category: 'meat',
    caloriesPer100g: 135,
    proteinPer100g: 20.36,
    fatPer100g: 3.63,
    carbsPer100g: 3.89,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 120 }]),
    sourceComment: 'USDA SR Legacy 169451',
  },
  {
    id: 'raw_beef_shoulder_raw',
    baseSlug: 'beef_shoulder',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כתף בקר נאה',
    nameEn: 'Beef shoulder, raw',
    category: 'meat',
    // Tzameret-only: not matched in USDA SR Legacy fetch. Values sourced from
    // Israeli butcher standard cut (Tnuva/Zogloveks reference, April 2026).
    caloriesPer100g: 180,
    proteinPer100g: 20.5,
    fatPer100g: 11,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'Tzameret / Israeli butcher reference, April 2026',
  },
  {
    id: 'raw_beef_shoulder_cooked',
    baseSlug: 'beef_shoulder',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'כתף בקר מבושלת',
    nameEn: 'Beef shoulder, cooked',
    category: 'meat',
    // Tzameret-only: braised shoulder, yield ~70% from raw.
    caloriesPer100g: 244,
    proteinPer100g: 27.5,
    fatPer100g: 14.5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 150 }]),
    sourceComment: 'Tzameret / Israeli butcher reference, April 2026',
  },
  {
    id: 'raw_lamb_shoulder_raw',
    baseSlug: 'lamb_shoulder',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כתף כבש נאה',
    nameEn: 'Lamb shoulder, raw',
    category: 'meat',
    caloriesPer100g: 272,
    proteinPer100g: 16.16,
    fatPer100g: 22.89,
    carbsPer100g: 0.24,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 175262',
  },
  {
    id: 'raw_lamb_shoulder_cooked',
    baseSlug: 'lamb_shoulder',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'כתף כבש מבושלת',
    nameEn: 'Lamb shoulder, cooked',
    category: 'meat',
    caloriesPer100g: 285,
    proteinPer100g: 34.06,
    fatPer100g: 15.5,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'מנה', nameEn: 'Serving', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 173814',
  },
  {
    id: 'raw_lamb_leg_raw',
    baseSlug: 'lamb_leg',
    state: 'raw',
    priority: 'P1',
    nameHe: 'ירך כבש נאה',
    nameEn: 'Lamb leg, raw',
    category: 'meat',
    caloriesPer100g: 206,
    proteinPer100g: 18.64,
    fatPer100g: 14.52,
    carbsPer100g: 0.13,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'נתח', nameEn: 'Cut', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 174342',
  },
  {
    id: 'raw_lamb_ground_raw',
    baseSlug: 'lamb_ground',
    state: 'raw',
    priority: 'P2',
    nameHe: 'בשר כבש טחון נא',
    nameEn: 'Lamb, ground, raw',
    category: 'meat',
    caloriesPer100g: 282,
    proteinPer100g: 16.56,
    fatPer100g: 23.41,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 500 }]),
    sourceComment: 'USDA SR Legacy 174370',
  },
  {
    id: 'raw_veal_cutlet_raw',
    baseSlug: 'veal_cutlet',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שניצל עגל נא',
    nameEn: 'Veal cutlet, raw',
    category: 'meat',
    caloriesPer100g: 117,
    proteinPer100g: 20.98,
    fatPer100g: 3.08,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Cutlet', unit: 'piece', grams: 100 }]),
    sourceComment: 'USDA SR Legacy 175268',
  },

  // ─────────────────────────────────────────────────────────────────────
  // FISH (13) — USDA SR Legacy (12) + Tzameret/label (1)
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_salmon_atlantic_raw',
    baseSlug: 'salmon_atlantic',
    state: 'raw',
    priority: 'P0',
    nameHe: 'סלמון נא',
    nameEn: 'Salmon, Atlantic, raw',
    category: 'fish',
    caloriesPer100g: 208,
    proteinPer100g: 20.42,
    fatPer100g: 13.42,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
      { nameHe: 'פילה גדול', nameEn: 'Large fillet', unit: 'piece', grams: 220 },
    ]),
    sourceComment: 'USDA SR Legacy 175167',
  },
  {
    id: 'raw_salmon_atlantic_cooked',
    baseSlug: 'salmon_atlantic',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'סלמון צלוי',
    nameEn: 'Salmon, Atlantic, cooked',
    category: 'fish',
    caloriesPer100g: 206,
    proteinPer100g: 22.1,
    fatPer100g: 12.35,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני (צלוי)', nameEn: 'Medium fillet cooked', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 175168',
  },
  {
    id: 'raw_tuna_yellowfin_raw',
    baseSlug: 'tuna_yellowfin',
    state: 'raw',
    priority: 'P0',
    nameHe: 'טונה צהובת סנפיר טריה',
    nameEn: 'Tuna, yellowfin, raw',
    category: 'fish',
    caloriesPer100g: 109,
    proteinPer100g: 24.4,
    fatPer100g: 0.49,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'סטייק', nameEn: 'Steak', unit: 'piece', grams: 170 }]),
    sourceComment: 'USDA SR Legacy 175159',
  },
  {
    id: 'raw_tuna_canned_water_raw',
    baseSlug: 'tuna_canned_water',
    state: 'raw',
    priority: 'P0',
    nameHe: 'טונה בשימורים במים',
    nameEn: 'Tuna, canned in water, drained',
    category: 'fish',
    caloriesPer100g: 116,
    proteinPer100g: 25.51,
    fatPer100g: 0.82,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קופסה קטנה (מסונן)', nameEn: 'Small can (drained)', unit: 'piece', grams: 120 },
      { nameHe: 'קופסה גדולה (מסונן)', nameEn: 'Large can (drained)', unit: 'piece', grams: 160 },
    ]),
    sourceComment: 'USDA SR Legacy 171986',
  },
  {
    id: 'raw_tilapia_raw',
    baseSlug: 'tilapia',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אמנון (טילפיה) נא',
    nameEn: 'Tilapia, raw',
    category: 'fish',
    caloriesPer100g: 96,
    proteinPer100g: 20.08,
    fatPer100g: 1.7,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 175176',
  },
  {
    id: 'raw_tilapia_cooked',
    baseSlug: 'tilapia',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'אמנון (טילפיה) צלוי',
    nameEn: 'Tilapia, cooked',
    category: 'fish',
    caloriesPer100g: 128,
    proteinPer100g: 26.15,
    fatPer100g: 2.65,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני (צלוי)', nameEn: 'Medium fillet cooked', unit: 'piece', grams: 120 },
    ]),
    sourceComment: 'USDA SR Legacy 175177',
  },
  {
    id: 'raw_sardine_canned_oil_raw',
    baseSlug: 'sardine_canned_oil',
    state: 'raw',
    priority: 'P1',
    nameHe: 'סרדינים בשמן',
    nameEn: 'Sardine, canned in oil, drained',
    category: 'fish',
    caloriesPer100g: 208,
    proteinPer100g: 24.62,
    fatPer100g: 11.45,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קופסה', nameEn: 'Can (drained)', unit: 'piece', grams: 90 },
    ]),
    sourceComment: 'USDA SR Legacy 175139',
  },
  {
    id: 'raw_mackerel_raw',
    baseSlug: 'mackerel',
    state: 'raw',
    priority: 'P2',
    nameHe: 'מקרל נא',
    nameEn: 'Mackerel, raw',
    category: 'fish',
    caloriesPer100g: 205,
    proteinPer100g: 18.6,
    fatPer100g: 13.89,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 175119',
  },
  {
    id: 'raw_cod_raw',
    baseSlug: 'cod',
    state: 'raw',
    priority: 'P2',
    nameHe: 'בקלה נא',
    nameEn: 'Cod, raw',
    category: 'fish',
    caloriesPer100g: 82,
    proteinPer100g: 17.81,
    fatPer100g: 0.67,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 171955',
  },
  {
    id: 'raw_shrimp_raw',
    baseSlug: 'shrimp',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שרימפס נאים',
    nameEn: 'Shrimp, raw',
    category: 'fish',
    caloriesPer100g: 85,
    proteinPer100g: 20.1,
    fatPer100g: 0.51,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'שרימפ בודד', nameEn: 'Single shrimp', unit: 'piece', grams: 7 },
    ]),
    sourceComment: 'USDA SR Legacy 175179',
  },
  {
    id: 'raw_trout_raw',
    baseSlug: 'trout',
    state: 'raw',
    priority: 'P2',
    nameHe: 'פורל נא',
    nameEn: 'Trout, rainbow, raw',
    category: 'fish',
    caloriesPer100g: 141,
    proteinPer100g: 19.94,
    fatPer100g: 6.18,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פילה בינוני', nameEn: 'Medium fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 173717',
  },
  {
    id: 'raw_salmon_smoked_raw',
    baseSlug: 'salmon_smoked',
    state: 'raw',
    priority: 'P1',
    nameHe: 'סלמון מעושן',
    nameEn: 'Salmon, smoked',
    category: 'fish',
    caloriesPer100g: 117,
    proteinPer100g: 18.28,
    fatPer100g: 4.32,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 15 },
      { nameHe: 'אריזה', nameEn: 'Package', unit: 'piece', grams: 100 },
    ]),
    sourceComment: 'USDA SR Legacy 173687',
  },
  {
    id: 'raw_sea_bream_raw',
    baseSlug: 'sea_bream',
    state: 'raw',
    priority: 'P1',
    nameHe: 'דניס נא',
    nameEn: 'Sea bream (denis), raw',
    category: 'fish',
    // Tzameret-only: common Israeli lean white fish; USDA has no direct match.
    // Values from published lean white fish profile (gilthead sea bream).
    caloriesPer100g: 135,
    proteinPer100g: 19.8,
    fatPer100g: 6,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'דג שלם בינוני', nameEn: 'Medium whole fish', unit: 'piece', grams: 350 },
      { nameHe: 'פילה', nameEn: 'Fillet', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'Tzameret / Israeli fishmonger reference, April 2026',
  },

  // ─────────────────────────────────────────────────────────────────────
  // DAIRY (18) — USDA SR Legacy (11) + Tzameret/label (7)
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_milk_1pct_raw',
    baseSlug: 'milk_1pct',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלב 1%',
    nameEn: 'Milk, 1%',
    category: 'dairy',
    caloriesPer100g: 42,
    proteinPer100g: 3.37,
    fatPer100g: 0.97,
    carbsPer100g: 4.99,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'piece', grams: 240 }]),
    sourceComment: 'USDA SR Legacy 170872',
  },
  {
    id: 'raw_milk_whole_raw',
    baseSlug: 'milk_whole',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלב 3.25%',
    nameEn: 'Milk, whole (3.25%)',
    category: 'dairy',
    caloriesPer100g: 61,
    proteinPer100g: 3.15,
    fatPer100g: 3.25,
    carbsPer100g: 4.8,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'piece', grams: 240 }]),
    sourceComment: 'USDA SR Legacy 171265',
  },
  {
    id: 'raw_milk_3pct_raw',
    baseSlug: 'milk_3pct',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חלב 3%',
    nameEn: 'Milk, 3% (Israeli standard)',
    category: 'dairy',
    // Tzameret-only: Israeli standard 3% milk (Tnuva/Tara label, April 2026).
    caloriesPer100g: 62,
    proteinPer100g: 3.3,
    fatPer100g: 3,
    carbsPer100g: 4.7,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'piece', grams: 240 }]),
    sourceComment: 'Tnuva/Tara label April 2026',
  },
  {
    id: 'raw_yogurt_plain_lowfat_raw',
    baseSlug: 'yogurt_plain_lowfat',
    state: 'raw',
    priority: 'P0',
    nameHe: 'יוגורט טבעי דל שומן',
    nameEn: 'Yogurt, plain, low fat',
    category: 'dairy',
    caloriesPer100g: 63,
    proteinPer100g: 5.25,
    fatPer100g: 1.55,
    carbsPer100g: 7.04,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 170886',
  },
  {
    id: 'raw_yogurt_plain_whole_raw',
    baseSlug: 'yogurt_plain_whole',
    state: 'raw',
    priority: 'P1',
    nameHe: 'יוגורט טבעי מלא',
    nameEn: 'Yogurt, plain, whole milk',
    category: 'dairy',
    caloriesPer100g: 61,
    proteinPer100g: 3.47,
    fatPer100g: 3.25,
    carbsPer100g: 4.66,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 150 }]),
    sourceComment: 'USDA SR Legacy 171284',
  },
  {
    id: 'raw_yogurt_greek_nonfat_raw',
    baseSlug: 'yogurt_greek_nonfat',
    state: 'raw',
    priority: 'P0',
    nameHe: 'יוגורט יווני 0%',
    nameEn: 'Yogurt, Greek, nonfat',
    category: 'dairy',
    caloriesPer100g: 54,
    proteinPer100g: 9.53,
    fatPer100g: 0.24,
    carbsPer100g: 3.43,
    fiberPer100g: 0.2,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 170 }]),
    sourceComment: 'USDA SR Legacy 171312',
  },
  {
    id: 'raw_yogurt_greek_whole_raw',
    baseSlug: 'yogurt_greek_whole',
    state: 'raw',
    priority: 'P1',
    nameHe: 'יוגורט יווני מלא',
    nameEn: 'Yogurt, Greek, whole milk',
    category: 'dairy',
    caloriesPer100g: 97,
    proteinPer100g: 9,
    fatPer100g: 5,
    carbsPer100g: 3.98,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 170 }]),
    sourceComment: 'USDA SR Legacy 171304',
  },
  {
    id: 'raw_feta_raw',
    baseSlug: 'feta',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת פטה',
    nameEn: 'Feta cheese',
    category: 'dairy',
    caloriesPer100g: 265,
    proteinPer100g: 14.21,
    fatPer100g: 21.49,
    carbsPer100g: 3.88,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'קובייה', nameEn: 'Cube', unit: 'piece', grams: 30 }]),
    sourceComment: 'USDA SR Legacy 173420',
  },
  {
    id: 'raw_mozzarella_raw',
    baseSlug: 'mozzarella',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת מוצרלה',
    nameEn: 'Mozzarella, part-skim',
    category: 'dairy',
    caloriesPer100g: 295,
    proteinPer100g: 23.75,
    fatPer100g: 19.78,
    carbsPer100g: 5.58,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 171244',
  },
  {
    id: 'raw_butter_raw',
    baseSlug: 'butter',
    state: 'raw',
    priority: 'P1',
    nameHe: 'חמאה',
    nameEn: 'Butter, unsalted',
    category: 'dairy',
    caloriesPer100g: 717,
    proteinPer100g: 0.85,
    fatPer100g: 81.11,
    carbsPer100g: 0.06,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 5 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 14 },
    ]),
    sourceComment: 'USDA SR Legacy 173430',
  },
  {
    id: 'raw_cream_cheese_full_raw',
    baseSlug: 'cream_cheese_full',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת שמנת (מלאה)',
    nameEn: 'Cream cheese',
    category: 'dairy',
    caloriesPer100g: 350,
    proteinPer100g: 6.15,
    fatPer100g: 34.44,
    carbsPer100g: 5.52,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף למריחה', nameEn: 'Spread tbsp', unit: 'tbsp', grams: 15 },
    ]),
    sourceComment: 'USDA SR Legacy 173418',
  },
  {
    id: 'raw_sour_cream_raw',
    baseSlug: 'sour_cream',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שמנת חמוצה',
    nameEn: 'Sour cream',
    category: 'dairy',
    caloriesPer100g: 198,
    proteinPer100g: 2.44,
    fatPer100g: 19.35,
    carbsPer100g: 4.63,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 12 }]),
    sourceComment: 'USDA SR Legacy 171257',
  },
  {
    id: 'raw_labneh_raw',
    baseSlug: 'labneh',
    state: 'raw',
    priority: 'P0',
    nameHe: 'לבנה 5%',
    nameEn: 'Labneh 5%',
    category: 'dairy',
    // Tzameret-only: Tnuva/Piraeus labneh 5% label (April 2026).
    caloriesPer100g: 112,
    proteinPer100g: 7,
    fatPer100g: 5,
    carbsPer100g: 4,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 200 }]),
    sourceComment: 'Tnuva labneh 5% label, April 2026',
  },
  {
    id: 'raw_white_cheese_5_raw',
    baseSlug: 'white_cheese_5',
    state: 'raw',
    priority: 'P0',
    nameHe: 'גבינה לבנה 5%',
    nameEn: 'White cheese 5% (gvina levana)',
    category: 'dairy',
    // Tzameret-only: Tnuva gvina levana 5% label (April 2026).
    caloriesPer100g: 100,
    proteinPer100g: 11,
    fatPer100g: 5,
    carbsPer100g: 3,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 250 }]),
    sourceComment: 'Tnuva white cheese 5% label, April 2026',
  },
  {
    id: 'raw_cottage_5_raw',
    baseSlug: 'cottage_5',
    state: 'raw',
    priority: 'P0',
    nameHe: "קוטג' 5%",
    nameEn: 'Cottage cheese 5%',
    category: 'dairy',
    // Tzameret-only: Tnuva cottage 5% label (April 2026).
    caloriesPer100g: 100,
    proteinPer100g: 11,
    fatPer100g: 5,
    carbsPer100g: 3,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 250 }]),
    sourceComment: 'Tnuva cottage 5% label, April 2026',
  },
  {
    id: 'raw_cottage_9_raw',
    baseSlug: 'cottage_9',
    state: 'raw',
    priority: 'P1',
    nameHe: "קוטג' 9%",
    nameEn: 'Cottage cheese 9%',
    category: 'dairy',
    // Tzameret-only: Tnuva cottage 9% label (April 2026).
    caloriesPer100g: 135,
    proteinPer100g: 11,
    fatPer100g: 9,
    carbsPer100g: 3,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'גביע', nameEn: 'Container', unit: 'piece', grams: 250 }]),
    sourceComment: 'Tnuva cottage 9% label, April 2026',
  },
  {
    id: 'raw_emek_raw',
    baseSlug: 'emek',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גבינת עמק',
    nameEn: 'Emek cheese',
    category: 'dairy',
    // Tzameret-only: Tnuva Emek yellow cheese label (April 2026).
    caloriesPer100g: 332,
    proteinPer100g: 25,
    fatPer100g: 25,
    carbsPer100g: 2,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 25 }]),
    sourceComment: 'Tnuva Emek label, April 2026',
  },
  // ─────────────────────────────────────────────────────────────────────
  // LEGUMES (11) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_lentils_raw',
    baseSlug: 'lentils',
    state: 'raw',
    priority: 'P0',
    nameHe: 'עדשים יבשות',
    nameEn: 'Lentils, dry',
    category: 'legumes',
    caloriesPer100g: 352,
    proteinPer100g: 24.63,
    fatPer100g: 1.06,
    carbsPer100g: 63.35,
    fiberPer100g: 10.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (יבש)', nameEn: 'Cup dry', unit: 'cup', grams: 192 },
      { nameHe: 'כף (יבש)', nameEn: 'Tbsp dry', unit: 'tbsp', grams: 12 },
    ]),
    sourceComment: 'USDA SR Legacy 172420',
  },
  {
    id: 'raw_lentils_cooked',
    baseSlug: 'lentils',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'עדשים מבושלות',
    nameEn: 'Lentils, cooked',
    category: 'legumes',
    caloriesPer100g: 116,
    proteinPer100g: 9.02,
    fatPer100g: 0.38,
    carbsPer100g: 20.13,
    fiberPer100g: 7.9,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 198 },
    ]),
    sourceComment: 'USDA SR Legacy 172421',
  },
  {
    id: 'raw_chickpeas_raw',
    baseSlug: 'chickpeas',
    state: 'raw',
    priority: 'P0',
    nameHe: 'גרגרי חומוס יבשים',
    nameEn: 'Chickpeas, dry',
    category: 'legumes',
    caloriesPer100g: 378,
    proteinPer100g: 20.47,
    fatPer100g: 6.04,
    carbsPer100g: 62.95,
    fiberPer100g: 12.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (יבש)', nameEn: 'Cup dry', unit: 'cup', grams: 200 },
    ]),
    sourceComment: 'USDA SR Legacy 173756',
  },
  {
    id: 'raw_chickpeas_cooked',
    baseSlug: 'chickpeas',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'גרגרי חומוס מבושלים',
    nameEn: 'Chickpeas, cooked',
    category: 'legumes',
    caloriesPer100g: 164,
    proteinPer100g: 8.86,
    fatPer100g: 2.59,
    carbsPer100g: 27.42,
    fiberPer100g: 7.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 164 },
    ]),
    sourceComment: 'USDA SR Legacy 173799',
  },
  {
    id: 'raw_white_beans_raw',
    baseSlug: 'white_beans',
    state: 'raw',
    priority: 'P1',
    nameHe: 'שעועית לבנה יבשה',
    nameEn: 'White beans, dry',
    category: 'legumes',
    caloriesPer100g: 333,
    proteinPer100g: 23.36,
    fatPer100g: 0.85,
    carbsPer100g: 60.27,
    fiberPer100g: 15.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (יבש)', nameEn: 'Cup dry', unit: 'cup', grams: 202 },
    ]),
    sourceComment: 'USDA SR Legacy 175202',
  },
  {
    id: 'raw_white_beans_cooked',
    baseSlug: 'white_beans',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'שעועית לבנה מבושלת',
    nameEn: 'White beans, cooked',
    category: 'legumes',
    caloriesPer100g: 139,
    proteinPer100g: 9.73,
    fatPer100g: 0.35,
    carbsPer100g: 25.09,
    fiberPer100g: 6.3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 179 },
    ]),
    sourceComment: 'USDA SR Legacy 175203',
  },
  {
    id: 'raw_black_beans_cooked',
    baseSlug: 'black_beans',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'שעועית שחורה מבושלת',
    nameEn: 'Black beans, cooked',
    category: 'legumes',
    caloriesPer100g: 132,
    proteinPer100g: 8.86,
    fatPer100g: 0.54,
    carbsPer100g: 23.71,
    fiberPer100g: 8.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 172 },
    ]),
    sourceComment: 'USDA SR Legacy 173735',
  },
  {
    id: 'raw_kidney_beans_cooked',
    baseSlug: 'kidney_beans',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'שעועית אדומה מבושלת',
    nameEn: 'Kidney beans, cooked',
    category: 'legumes',
    caloriesPer100g: 127,
    proteinPer100g: 8.67,
    fatPer100g: 0.5,
    carbsPer100g: 22.8,
    fiberPer100g: 6.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 177 },
    ]),
    sourceComment: 'USDA SR Legacy 173740',
  },
  {
    id: 'raw_fava_beans_cooked',
    baseSlug: 'fava_beans',
    state: 'cooked',
    priority: 'P2',
    nameHe: 'פול מבושל',
    nameEn: 'Fava beans, cooked',
    category: 'legumes',
    caloriesPer100g: 110,
    proteinPer100g: 7.6,
    fatPer100g: 0.4,
    carbsPer100g: 19.65,
    fiberPer100g: 5.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 170 },
    ]),
    sourceComment: 'USDA SR Legacy 173753',
  },
  {
    id: 'raw_mung_beans_cooked',
    baseSlug: 'mung_beans',
    state: 'cooked',
    priority: 'P2',
    nameHe: 'שעועית מאש מבושלת',
    nameEn: 'Mung beans, cooked',
    category: 'legumes',
    caloriesPer100g: 105,
    proteinPer100g: 7.02,
    fatPer100g: 0.38,
    carbsPer100g: 19.15,
    fiberPer100g: 7.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 202 },
    ]),
    sourceComment: 'USDA SR Legacy 174257',
  },
  {
    id: 'raw_tofu_firm_raw',
    baseSlug: 'tofu_firm',
    state: 'raw',
    priority: 'P1',
    nameHe: 'טופו קשה',
    nameEn: 'Tofu, firm',
    category: 'legumes',
    caloriesPer100g: 144,
    proteinPer100g: 17.27,
    fatPer100g: 8.72,
    carbsPer100g: 2.78,
    fiberPer100g: 2.3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קובייה', nameEn: 'Cube', unit: 'piece', grams: 30 },
      { nameHe: 'חבילה', nameEn: 'Package', unit: 'piece', grams: 350 },
    ]),
    sourceComment: 'USDA SR Legacy 172475',
  },
  // ─────────────────────────────────────────────────────────────────────
  // GRAINS (17) — USDA SR Legacy
  // Note: oats_dry, oatmeal_cooked, tortilla_flour skipped — broken USDA
  // fetches (oil/dry-as-cooked/pesto). Pin in follow-up PR.
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_rice_white_raw',
    baseSlug: 'rice_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'אורז לבן יבש',
    nameEn: 'White rice, dry',
    category: 'grains',
    caloriesPer100g: 365,
    proteinPer100g: 7.13,
    fatPer100g: 0.66,
    carbsPer100g: 79.95,
    fiberPer100g: 1.3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (יבש)', nameEn: 'Cup dry', unit: 'cup', grams: 185 },
    ]),
    sourceComment: 'USDA SR Legacy 169756',
  },
  {
    id: 'raw_rice_white_cooked',
    baseSlug: 'rice_white',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'אורז לבן מבושל',
    nameEn: 'White rice, cooked',
    category: 'grains',
    caloriesPer100g: 130,
    proteinPer100g: 2.69,
    fatPer100g: 0.28,
    carbsPer100g: 28.17,
    fiberPer100g: 0.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 158 },
    ]),
    sourceComment: 'USDA SR Legacy 169757',
  },
  {
    id: 'raw_rice_basmati_cooked',
    baseSlug: 'rice_basmati',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'אורז בסמטי מבושל',
    nameEn: 'Basmati rice, cooked',
    category: 'grains',
    caloriesPer100g: 123,
    proteinPer100g: 2.91,
    fatPer100g: 0.37,
    carbsPer100g: 26.05,
    fiberPer100g: 0.9,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 158 },
    ]),
    sourceComment: 'USDA SR Legacy 169708',
  },
  {
    id: 'raw_rice_brown_cooked',
    baseSlug: 'rice_brown',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'אורז מלא מבושל',
    nameEn: 'Brown rice, cooked',
    category: 'grains',
    caloriesPer100g: 123,
    proteinPer100g: 2.74,
    fatPer100g: 0.97,
    carbsPer100g: 25.58,
    fiberPer100g: 1.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 195 },
    ]),
    sourceComment: 'USDA SR Legacy 169704',
  },
  {
    id: 'raw_pasta_raw',
    baseSlug: 'pasta',
    state: 'raw',
    priority: 'P0',
    nameHe: 'פסטה יבשה',
    nameEn: 'Pasta, dry',
    category: 'grains',
    caloriesPer100g: 371,
    proteinPer100g: 13.04,
    fatPer100g: 1.51,
    carbsPer100g: 74.67,
    fiberPer100g: 3.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'מנה (יבש)', nameEn: 'Portion dry', unit: 'portion', grams: 75 },
    ]),
    sourceComment: 'USDA SR Legacy 168927',
  },
  {
    id: 'raw_pasta_cooked',
    baseSlug: 'pasta',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'פסטה מבושלת',
    nameEn: 'Pasta, cooked',
    category: 'grains',
    caloriesPer100g: 158,
    proteinPer100g: 5.8,
    fatPer100g: 0.93,
    carbsPer100g: 30.86,
    fiberPer100g: 1.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 140 },
    ]),
    sourceComment: 'USDA SR Legacy 168928',
  },
  {
    id: 'raw_pasta_whole_wheat_cooked',
    baseSlug: 'pasta_whole_wheat',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'פסטה מחיטה מלאה מבושלת',
    nameEn: 'Whole wheat pasta, cooked',
    category: 'grains',
    caloriesPer100g: 159,
    proteinPer100g: 5.82,
    fatPer100g: 1.5,
    carbsPer100g: 31.51,
    fiberPer100g: 4.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 140 },
    ]),
    sourceComment: 'USDA SR Legacy 168916',
  },
  {
    id: 'raw_quinoa_raw',
    baseSlug: 'quinoa',
    state: 'raw',
    priority: 'P1',
    nameHe: 'קינואה יבשה',
    nameEn: 'Quinoa, dry',
    category: 'grains',
    caloriesPer100g: 368,
    proteinPer100g: 14.12,
    fatPer100g: 6.07,
    carbsPer100g: 64.16,
    fiberPer100g: 7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (יבש)', nameEn: 'Cup dry', unit: 'cup', grams: 170 },
    ]),
    sourceComment: 'USDA SR Legacy 168874',
  },
  {
    id: 'raw_quinoa_cooked',
    baseSlug: 'quinoa',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'קינואה מבושלת',
    nameEn: 'Quinoa, cooked',
    category: 'grains',
    caloriesPer100g: 120,
    proteinPer100g: 4.4,
    fatPer100g: 1.92,
    carbsPer100g: 21.3,
    fiberPer100g: 2.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 185 },
    ]),
    sourceComment: 'USDA SR Legacy 168917',
  },
  {
    id: 'raw_bulgur_cooked',
    baseSlug: 'bulgur',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'בורגול מבושל',
    nameEn: 'Bulgur, cooked',
    category: 'grains',
    caloriesPer100g: 83,
    proteinPer100g: 3.08,
    fatPer100g: 0.24,
    carbsPer100g: 18.58,
    fiberPer100g: 4.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 182 },
    ]),
    sourceComment: 'USDA SR Legacy 170287',
  },
  {
    id: 'raw_couscous_cooked',
    baseSlug: 'couscous',
    state: 'cooked',
    priority: 'P1',
    nameHe: 'קוסקוס מבושל',
    nameEn: 'Couscous, cooked',
    category: 'grains',
    caloriesPer100g: 112,
    proteinPer100g: 3.79,
    fatPer100g: 0.16,
    carbsPer100g: 23.22,
    fiberPer100g: 1.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 157 },
    ]),
    sourceComment: 'USDA SR Legacy 169700',
  },
  {
    id: 'raw_barley_cooked',
    baseSlug: 'barley',
    state: 'cooked',
    priority: 'P2',
    nameHe: 'שעורה מבושלת',
    nameEn: 'Barley, cooked',
    category: 'grains',
    caloriesPer100g: 123,
    proteinPer100g: 2.26,
    fatPer100g: 0.44,
    carbsPer100g: 28.22,
    fiberPer100g: 3.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 157 },
    ]),
    sourceComment: 'USDA SR Legacy 170285',
  },
  {
    id: 'raw_buckwheat_cooked',
    baseSlug: 'buckwheat',
    state: 'cooked',
    priority: 'P2',
    nameHe: 'כוסמת מבושלת',
    nameEn: 'Buckwheat, cooked',
    category: 'grains',
    caloriesPer100g: 92,
    proteinPer100g: 3.38,
    fatPer100g: 0.62,
    carbsPer100g: 19.94,
    fiberPer100g: 2.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (מבושל)', nameEn: 'Cup cooked', unit: 'cup', grams: 168 },
    ]),
    sourceComment: 'USDA SR Legacy 170686',
  },
  {
    id: 'raw_bread_white_raw',
    baseSlug: 'bread_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'לחם לבן',
    nameEn: 'White bread',
    category: 'grains',
    caloriesPer100g: 290,
    proteinPer100g: 9,
    fatPer100g: 4,
    carbsPer100g: 54.5,
    fiberPer100g: 2.9,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 174925',
  },
  {
    id: 'raw_bread_whole_wheat_raw',
    baseSlug: 'bread_whole_wheat',
    state: 'raw',
    priority: 'P0',
    nameHe: 'לחם מחיטה מלאה',
    nameEn: 'Whole wheat bread',
    category: 'grains',
    caloriesPer100g: 252,
    proteinPer100g: 12.45,
    fatPer100g: 3.5,
    carbsPer100g: 42.71,
    fiberPer100g: 6,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'slice', grams: 32 }]),
    sourceComment: 'USDA SR Legacy 172688',
  },
  {
    id: 'raw_bread_pita_white_raw',
    baseSlug: 'bread_pita_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'פיתה לבנה',
    nameEn: 'Pita, white',
    category: 'grains',
    caloriesPer100g: 275,
    proteinPer100g: 9.1,
    fatPer100g: 1.2,
    carbsPer100g: 55.7,
    fiberPer100g: 2.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פיתה קטנה', nameEn: 'Small pita', unit: 'piece', grams: 28 },
      { nameHe: 'פיתה גדולה', nameEn: 'Large pita', unit: 'piece', grams: 60 },
    ]),
    sourceComment: 'USDA SR Legacy 174915',
  },
  {
    id: 'raw_bread_pita_whole_wheat_raw',
    baseSlug: 'bread_pita_whole_wheat',
    state: 'raw',
    priority: 'P1',
    nameHe: 'פיתה מחיטה מלאה',
    nameEn: 'Pita, whole wheat',
    category: 'grains',
    caloriesPer100g: 262,
    proteinPer100g: 9.8,
    fatPer100g: 1.71,
    carbsPer100g: 55.89,
    fiberPer100g: 6.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פיתה גדולה', nameEn: 'Large pita', unit: 'piece', grams: 64 },
    ]),
    sourceComment: 'USDA SR Legacy 174916',
  },
  // ─────────────────────────────────────────────────────────────────────
  // VEGETABLES (29) — USDA SR Legacy
  // Note: sweet_potato raw skipped — broken USDA fetch (returned puffs).
  // Pin in follow-up PR.
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_tomato_raw',
    baseSlug: 'tomato',
    state: 'raw',
    priority: 'P0',
    nameHe: 'עגבנייה',
    nameEn: 'Tomato',
    category: 'vegetables',
    caloriesPer100g: 18,
    proteinPer100g: 0.88,
    fatPer100g: 0.2,
    carbsPer100g: 3.89,
    fiberPer100g: 1.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'עגבנייה בינונית', nameEn: 'Medium tomato', unit: 'piece', grams: 123 },
      { nameHe: 'עגבנייה גדולה', nameEn: 'Large tomato', unit: 'piece', grams: 182 },
    ]),
    sourceComment: 'USDA SR Legacy 170457',
  },
  {
    id: 'raw_cherry_tomato_raw',
    baseSlug: 'cherry_tomato',
    state: 'raw',
    priority: 'P1',
    nameHe: 'עגבנייה שרי',
    nameEn: 'Cherry tomato',
    category: 'vegetables',
    caloriesPer100g: 18,
    proteinPer100g: 0.88,
    fatPer100g: 0.2,
    carbsPer100g: 3.89,
    fiberPer100g: 1.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'עגבנייה אחת', nameEn: 'One cherry', unit: 'piece', grams: 17 },
      { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 149 },
    ]),
    sourceComment: 'USDA SR Legacy 170457',
  },
  {
    id: 'raw_cucumber_raw',
    baseSlug: 'cucumber',
    state: 'raw',
    priority: 'P0',
    nameHe: 'מלפפון',
    nameEn: 'Cucumber',
    category: 'vegetables',
    caloriesPer100g: 15,
    proteinPer100g: 0.65,
    fatPer100g: 0.11,
    carbsPer100g: 3.63,
    fiberPer100g: 0.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'מלפפון קטן', nameEn: 'Small cucumber', unit: 'piece', grams: 80 },
      { nameHe: 'מלפפון בינוני', nameEn: 'Medium cucumber', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 168409',
  },
  {
    id: 'raw_bell_pepper_red_raw',
    baseSlug: 'bell_pepper_red',
    state: 'raw',
    priority: 'P0',
    nameHe: 'פלפל אדום',
    nameEn: 'Red bell pepper',
    category: 'vegetables',
    caloriesPer100g: 26,
    proteinPer100g: 0.99,
    fatPer100g: 0.3,
    carbsPer100g: 6.03,
    fiberPer100g: 2.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פלפל בינוני', nameEn: 'Medium pepper', unit: 'piece', grams: 119 },
    ]),
    sourceComment: 'USDA SR Legacy 170108',
  },
  {
    id: 'raw_bell_pepper_green_raw',
    baseSlug: 'bell_pepper_green',
    state: 'raw',
    priority: 'P0',
    nameHe: 'פלפל ירוק',
    nameEn: 'Green bell pepper',
    category: 'vegetables',
    caloriesPer100g: 20,
    proteinPer100g: 0.86,
    fatPer100g: 0.17,
    carbsPer100g: 4.64,
    fiberPer100g: 1.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פלפל בינוני', nameEn: 'Medium pepper', unit: 'piece', grams: 119 },
    ]),
    sourceComment: 'USDA SR Legacy 170427',
  },
  {
    id: 'raw_bell_pepper_yellow_raw',
    baseSlug: 'bell_pepper_yellow',
    state: 'raw',
    priority: 'P1',
    nameHe: 'פלפל צהוב',
    nameEn: 'Yellow bell pepper',
    category: 'vegetables',
    caloriesPer100g: 27,
    proteinPer100g: 1,
    fatPer100g: 0.21,
    carbsPer100g: 6.32,
    fiberPer100g: 0.9,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פלפל בינוני', nameEn: 'Medium pepper', unit: 'piece', grams: 119 },
    ]),
    sourceComment: 'USDA SR Legacy 169383',
  },
  {
    id: 'raw_eggplant_raw',
    baseSlug: 'eggplant',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חציל',
    nameEn: 'Eggplant',
    category: 'vegetables',
    caloriesPer100g: 25,
    proteinPer100g: 0.98,
    fatPer100g: 0.18,
    carbsPer100g: 5.88,
    fiberPer100g: 3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חציל בינוני', nameEn: 'Medium eggplant', unit: 'piece', grams: 458 },
    ]),
    sourceComment: 'USDA SR Legacy 169228',
  },
  {
    id: 'raw_zucchini_raw',
    baseSlug: 'zucchini',
    state: 'raw',
    priority: 'P0',
    nameHe: 'קישוא',
    nameEn: 'Zucchini',
    category: 'vegetables',
    caloriesPer100g: 17,
    proteinPer100g: 1.21,
    fatPer100g: 0.32,
    carbsPer100g: 3.11,
    fiberPer100g: 1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קישוא בינוני', nameEn: 'Medium zucchini', unit: 'piece', grams: 196 },
    ]),
    sourceComment: 'USDA SR Legacy 169291',
  },
  {
    id: 'raw_broccoli_raw',
    baseSlug: 'broccoli',
    state: 'raw',
    priority: 'P0',
    nameHe: 'ברוקולי',
    nameEn: 'Broccoli',
    category: 'vegetables',
    caloriesPer100g: 34,
    proteinPer100g: 2.82,
    fatPer100g: 0.37,
    carbsPer100g: 6.64,
    fiberPer100g: 2.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קצוץ', nameEn: 'Cup chopped', unit: 'cup', grams: 91 },
      { nameHe: 'תפרחת', nameEn: 'Floret', unit: 'piece', grams: 11 },
    ]),
    sourceComment: 'USDA SR Legacy 170379',
  },
  {
    id: 'raw_cauliflower_raw',
    baseSlug: 'cauliflower',
    state: 'raw',
    priority: 'P0',
    nameHe: 'כרובית',
    nameEn: 'Cauliflower',
    category: 'vegetables',
    caloriesPer100g: 25,
    proteinPer100g: 1.92,
    fatPer100g: 0.28,
    carbsPer100g: 4.97,
    fiberPer100g: 2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קצוץ', nameEn: 'Cup chopped', unit: 'cup', grams: 107 },
    ]),
    sourceComment: 'USDA SR Legacy 169986',
  },
  {
    id: 'raw_spinach_raw',
    baseSlug: 'spinach',
    state: 'raw',
    priority: 'P0',
    nameHe: 'תרד',
    nameEn: 'Spinach',
    category: 'vegetables',
    caloriesPer100g: 23,
    proteinPer100g: 2.86,
    fatPer100g: 0.39,
    carbsPer100g: 3.63,
    fiberPer100g: 2.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס (לא דחוס)', nameEn: 'Cup loose', unit: 'cup', grams: 30 },
    ]),
    sourceComment: 'USDA SR Legacy 168462',
  },
  {
    id: 'raw_carrot_raw',
    baseSlug: 'carrot',
    state: 'raw',
    priority: 'P0',
    nameHe: 'גזר',
    nameEn: 'Carrot',
    category: 'vegetables',
    caloriesPer100g: 41,
    proteinPer100g: 0.93,
    fatPer100g: 0.24,
    carbsPer100g: 9.58,
    fiberPer100g: 2.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'גזר בינוני', nameEn: 'Medium carrot', unit: 'piece', grams: 61 },
    ]),
    sourceComment: 'USDA SR Legacy 170393',
  },
  {
    id: 'raw_onion_raw',
    baseSlug: 'onion',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בצל',
    nameEn: 'Onion',
    category: 'vegetables',
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    fatPer100g: 0.1,
    carbsPer100g: 9.34,
    fiberPer100g: 1.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'בצל בינוני', nameEn: 'Medium onion', unit: 'piece', grams: 110 },
    ]),
    sourceComment: 'USDA SR Legacy 170000',
  },
  {
    id: 'raw_onion_red_raw',
    baseSlug: 'onion_red',
    state: 'raw',
    priority: 'P1',
    nameHe: 'בצל סגול',
    nameEn: 'Red onion',
    category: 'vegetables',
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    fatPer100g: 0.1,
    carbsPer100g: 9.34,
    fiberPer100g: 1.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'בצל בינוני', nameEn: 'Medium onion', unit: 'piece', grams: 110 },
    ]),
    sourceComment: 'USDA SR Legacy 170000 (red onion uses same baseline)',
  },
  {
    id: 'raw_garlic_raw',
    baseSlug: 'garlic',
    state: 'raw',
    priority: 'P0',
    nameHe: 'שום',
    nameEn: 'Garlic',
    category: 'vegetables',
    caloriesPer100g: 149,
    proteinPer100g: 6.36,
    fatPer100g: 0.5,
    carbsPer100g: 33.06,
    fiberPer100g: 2.1,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'שן שום', nameEn: 'Clove', unit: 'piece', grams: 3 }]),
    sourceComment: 'USDA SR Legacy 169230',
  },
  {
    id: 'raw_potato_raw',
    baseSlug: 'potato',
    state: 'raw',
    priority: 'P0',
    nameHe: 'תפוח אדמה נא',
    nameEn: 'Potato, raw',
    category: 'vegetables',
    caloriesPer100g: 58,
    proteinPer100g: 2.57,
    fatPer100g: 0.1,
    carbsPer100g: 12.44,
    fiberPer100g: 2.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'תפוח אדמה בינוני', nameEn: 'Medium potato', unit: 'piece', grams: 173 },
    ]),
    sourceComment: 'USDA SR Legacy 170032',
  },
  {
    id: 'raw_potato_cooked',
    baseSlug: 'potato',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'תפוח אדמה מבושל',
    nameEn: 'Potato, boiled',
    category: 'vegetables',
    caloriesPer100g: 87,
    proteinPer100g: 1.87,
    fatPer100g: 0.1,
    carbsPer100g: 20.13,
    fiberPer100g: 1.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'תפוח אדמה בינוני', nameEn: 'Medium potato', unit: 'piece', grams: 167 },
    ]),
    sourceComment: 'USDA SR Legacy 170438',
  },
  {
    id: 'raw_sweet_potato_cooked',
    baseSlug: 'sweet_potato',
    state: 'cooked',
    priority: 'P0',
    nameHe: 'בטטה אפויה',
    nameEn: 'Sweet potato, baked',
    category: 'vegetables',
    caloriesPer100g: 90,
    proteinPer100g: 2.01,
    fatPer100g: 0.15,
    carbsPer100g: 20.71,
    fiberPer100g: 3.3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'בטטה בינונית', nameEn: 'Medium sweet potato', unit: 'piece', grams: 151 },
    ]),
    sourceComment: 'USDA SR Legacy 168483',
  },
  {
    id: 'raw_lettuce_romaine_raw',
    baseSlug: 'lettuce_romaine',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חסה רומית',
    nameEn: 'Romaine lettuce',
    category: 'vegetables',
    caloriesPer100g: 17,
    proteinPer100g: 1.23,
    fatPer100g: 0.3,
    carbsPer100g: 3.29,
    fiberPer100g: 2.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קצוץ', nameEn: 'Cup shredded', unit: 'cup', grams: 47 },
    ]),
    sourceComment: 'USDA SR Legacy 169247',
  },
  {
    id: 'raw_cabbage_white_raw',
    baseSlug: 'cabbage_white',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כרוב לבן',
    nameEn: 'White cabbage',
    category: 'vegetables',
    caloriesPer100g: 25,
    proteinPer100g: 1.28,
    fatPer100g: 0.1,
    carbsPer100g: 5.8,
    fiberPer100g: 2.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קצוץ', nameEn: 'Cup shredded', unit: 'cup', grams: 89 },
    ]),
    sourceComment: 'USDA SR Legacy 169975',
  },
  {
    id: 'raw_cabbage_red_raw',
    baseSlug: 'cabbage_red',
    state: 'raw',
    priority: 'P1',
    nameHe: 'כרוב אדום',
    nameEn: 'Red cabbage',
    category: 'vegetables',
    caloriesPer100g: 31,
    proteinPer100g: 1.43,
    fatPer100g: 0.16,
    carbsPer100g: 7.37,
    fiberPer100g: 2.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קצוץ', nameEn: 'Cup shredded', unit: 'cup', grams: 89 },
    ]),
    sourceComment: 'USDA SR Legacy 169977',
  },
  {
    id: 'raw_kale_raw',
    baseSlug: 'kale',
    state: 'raw',
    priority: 'P1',
    nameHe: 'קייל',
    nameEn: 'Kale',
    category: 'vegetables',
    caloriesPer100g: 35,
    proteinPer100g: 2.92,
    fatPer100g: 1.49,
    carbsPer100g: 4.42,
    fiberPer100g: 4.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קצוץ', nameEn: 'Cup chopped', unit: 'cup', grams: 21 },
    ]),
    sourceComment: 'USDA SR Legacy 168421',
  },
  {
    id: 'raw_mushroom_white_raw',
    baseSlug: 'mushroom_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'פטריות שמפיניון',
    nameEn: 'White mushrooms',
    category: 'vegetables',
    caloriesPer100g: 22,
    proteinPer100g: 3.09,
    fatPer100g: 0.34,
    carbsPer100g: 3.26,
    fiberPer100g: 1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'פטרייה בינונית', nameEn: 'Medium mushroom', unit: 'piece', grams: 18 },
      { nameHe: 'כוס פרוס', nameEn: 'Cup sliced', unit: 'cup', grams: 70 },
    ]),
    sourceComment: 'USDA SR Legacy 169251',
  },
  {
    id: 'raw_corn_kernels_raw',
    baseSlug: 'corn_kernels',
    state: 'raw',
    priority: 'P1',
    nameHe: 'תירס',
    nameEn: 'Corn kernels',
    category: 'vegetables',
    caloriesPer100g: 86,
    proteinPer100g: 3.27,
    fatPer100g: 1.35,
    carbsPer100g: 18.7,
    fiberPer100g: 2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 154 },
      { nameHe: 'קלח בינוני', nameEn: 'Medium cob', unit: 'piece', grams: 103 },
    ]),
    sourceComment: 'USDA SR Legacy 169998',
  },
  {
    id: 'raw_green_beans_raw',
    baseSlug: 'green_beans',
    state: 'raw',
    priority: 'P1',
    nameHe: 'שעועית ירוקה',
    nameEn: 'Green beans',
    category: 'vegetables',
    caloriesPer100g: 31,
    proteinPer100g: 1.83,
    fatPer100g: 0.22,
    carbsPer100g: 6.97,
    fiberPer100g: 2.7,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 100 }]),
    sourceComment: 'USDA SR Legacy 169961',
  },
  {
    id: 'raw_peas_raw',
    baseSlug: 'peas',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אפונה',
    nameEn: 'Green peas',
    category: 'vegetables',
    caloriesPer100g: 81,
    proteinPer100g: 5.42,
    fatPer100g: 0.4,
    carbsPer100g: 14.45,
    fiberPer100g: 5.7,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 145 }]),
    sourceComment: 'USDA SR Legacy 170419',
  },
  {
    id: 'raw_celery_raw',
    baseSlug: 'celery',
    state: 'raw',
    priority: 'P1',
    nameHe: 'סלרי',
    nameEn: 'Celery',
    category: 'vegetables',
    caloriesPer100g: 14,
    proteinPer100g: 0.69,
    fatPer100g: 0.17,
    carbsPer100g: 2.97,
    fiberPer100g: 1.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'גבעול בינוני', nameEn: 'Medium stalk', unit: 'piece', grams: 40 },
    ]),
    sourceComment: 'USDA SR Legacy 169988',
  },
  {
    id: 'raw_radish_raw',
    baseSlug: 'radish',
    state: 'raw',
    priority: 'P2',
    nameHe: 'צנון',
    nameEn: 'Radish',
    category: 'vegetables',
    caloriesPer100g: 16,
    proteinPer100g: 0.68,
    fatPer100g: 0.1,
    carbsPer100g: 3.4,
    fiberPer100g: 1.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'צנון אחד', nameEn: 'One radish', unit: 'piece', grams: 4.5 },
    ]),
    sourceComment: 'USDA SR Legacy 169276',
  },
  {
    id: 'raw_beet_raw',
    baseSlug: 'beet',
    state: 'raw',
    priority: 'P2',
    nameHe: 'סלק',
    nameEn: 'Beet',
    category: 'vegetables',
    caloriesPer100g: 43,
    proteinPer100g: 1.61,
    fatPer100g: 0.17,
    carbsPer100g: 9.56,
    fiberPer100g: 2.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'סלק בינוני', nameEn: 'Medium beet', unit: 'piece', grams: 82 },
    ]),
    sourceComment: 'USDA SR Legacy 169145',
  },
  // ─────────────────────────────────────────────────────────────────────
  // FRUITS (25) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_apple_raw',
    baseSlug: 'apple',
    state: 'raw',
    priority: 'P0',
    nameHe: 'תפוח עץ',
    nameEn: 'Apple, raw',
    category: 'fruits',
    caloriesPer100g: 48,
    proteinPer100g: 0.27,
    fatPer100g: 0.13,
    carbsPer100g: 12.76,
    fiberPer100g: 1.3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'תפוח בינוני', nameEn: 'Medium apple', unit: 'piece', grams: 161 },
      { nameHe: 'תפוח גדול', nameEn: 'Large apple', unit: 'piece', grams: 216 },
    ]),
    sourceComment: 'USDA SR Legacy 171689',
  },
  {
    id: 'raw_banana_raw',
    baseSlug: 'banana',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בננה',
    nameEn: 'Banana, raw',
    category: 'fruits',
    caloriesPer100g: 89,
    proteinPer100g: 1.09,
    fatPer100g: 0.33,
    carbsPer100g: 22.84,
    fiberPer100g: 2.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'בננה בינונית', nameEn: 'Medium banana', unit: 'piece', grams: 118 },
      { nameHe: 'בננה גדולה', nameEn: 'Large banana', unit: 'piece', grams: 136 },
    ]),
    sourceComment: 'USDA SR Legacy 173944',
  },
  {
    id: 'raw_orange_raw',
    baseSlug: 'orange',
    state: 'raw',
    priority: 'P0',
    nameHe: 'תפוז',
    nameEn: 'Orange, raw',
    category: 'fruits',
    caloriesPer100g: 47,
    proteinPer100g: 0.94,
    fatPer100g: 0.12,
    carbsPer100g: 11.75,
    fiberPer100g: 2.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'תפוז בינוני', nameEn: 'Medium orange', unit: 'piece', grams: 131 },
      { nameHe: 'תפוז גדול', nameEn: 'Large orange', unit: 'piece', grams: 184 },
    ]),
    sourceComment: 'USDA SR Legacy 169097',
  },
  {
    id: 'raw_clementine_raw',
    baseSlug: 'clementine',
    state: 'raw',
    priority: 'P1',
    nameHe: 'קלמנטינה',
    nameEn: 'Clementine (mandarin), raw',
    category: 'fruits',
    caloriesPer100g: 53,
    proteinPer100g: 0.81,
    fatPer100g: 0.31,
    carbsPer100g: 13.34,
    fiberPer100g: 1.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קלמנטינה אחת', nameEn: 'One clementine', unit: 'piece', grams: 74 },
    ]),
    sourceComment: 'USDA SR Legacy 169105',
  },
  {
    id: 'raw_pear_raw',
    baseSlug: 'pear',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אגס',
    nameEn: 'Pear, raw',
    category: 'fruits',
    caloriesPer100g: 57,
    proteinPer100g: 0.36,
    fatPer100g: 0.14,
    carbsPer100g: 15.23,
    fiberPer100g: 3.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'אגס בינוני', nameEn: 'Medium pear', unit: 'piece', grams: 178 },
    ]),
    sourceComment: 'USDA SR Legacy 169118',
  },
  {
    id: 'raw_watermelon_raw',
    baseSlug: 'watermelon',
    state: 'raw',
    priority: 'P0',
    nameHe: 'אבטיח',
    nameEn: 'Watermelon, raw',
    category: 'fruits',
    caloriesPer100g: 30,
    proteinPer100g: 0.61,
    fatPer100g: 0.15,
    carbsPer100g: 7.55,
    fiberPer100g: 0.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קוביות', nameEn: 'Cup diced', unit: 'cup', grams: 152 },
      { nameHe: 'פלח', nameEn: 'Wedge', unit: 'piece', grams: 286 },
    ]),
    sourceComment: 'USDA SR Legacy 167765',
  },
  {
    id: 'raw_melon_cantaloupe_raw',
    baseSlug: 'melon_cantaloupe',
    state: 'raw',
    priority: 'P1',
    nameHe: 'מלון',
    nameEn: 'Cantaloupe melon, raw',
    category: 'fruits',
    caloriesPer100g: 34,
    proteinPer100g: 0.84,
    fatPer100g: 0.19,
    carbsPer100g: 8.16,
    fiberPer100g: 0.9,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קוביות', nameEn: 'Cup diced', unit: 'cup', grams: 160 },
      { nameHe: 'פלח', nameEn: 'Wedge', unit: 'piece', grams: 69 },
    ]),
    sourceComment: 'USDA SR Legacy 169092',
  },
  {
    id: 'raw_grapes_raw',
    baseSlug: 'grapes',
    state: 'raw',
    priority: 'P0',
    nameHe: 'ענבים',
    nameEn: 'Grapes, raw',
    category: 'fruits',
    caloriesPer100g: 69,
    proteinPer100g: 0.72,
    fatPer100g: 0.16,
    carbsPer100g: 18.1,
    fiberPer100g: 0.9,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 151 },
      { nameHe: 'ענב אחד', nameEn: 'One grape', unit: 'piece', grams: 5 },
    ]),
    sourceComment: 'USDA SR Legacy 174683',
  },
  {
    id: 'raw_strawberry_raw',
    baseSlug: 'strawberry',
    state: 'raw',
    priority: 'P0',
    nameHe: 'תות שדה',
    nameEn: 'Strawberries, raw',
    category: 'fruits',
    caloriesPer100g: 32,
    proteinPer100g: 0.67,
    fatPer100g: 0.3,
    carbsPer100g: 7.68,
    fiberPer100g: 2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס שלמים', nameEn: 'Cup whole', unit: 'cup', grams: 144 },
      { nameHe: 'תות בינוני', nameEn: 'Medium berry', unit: 'piece', grams: 12 },
    ]),
    sourceComment: 'USDA SR Legacy 167762',
  },
  {
    id: 'raw_blueberry_raw',
    baseSlug: 'blueberry',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אוכמניות',
    nameEn: 'Blueberries, raw',
    category: 'fruits',
    caloriesPer100g: 57,
    proteinPer100g: 0.74,
    fatPer100g: 0.33,
    carbsPer100g: 14.49,
    fiberPer100g: 2.4,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 148 }]),
    sourceComment: 'USDA SR Legacy 171711',
  },
  {
    id: 'raw_mango_raw',
    baseSlug: 'mango',
    state: 'raw',
    priority: 'P1',
    nameHe: 'מנגו',
    nameEn: 'Mango, raw',
    category: 'fruits',
    caloriesPer100g: 60,
    proteinPer100g: 0.82,
    fatPer100g: 0.38,
    carbsPer100g: 14.98,
    fiberPer100g: 1.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'מנגו בינוני', nameEn: 'Medium mango', unit: 'piece', grams: 200 },
      { nameHe: 'כוס קוביות', nameEn: 'Cup diced', unit: 'cup', grams: 165 },
    ]),
    sourceComment: 'USDA SR Legacy 169910',
  },
  {
    id: 'raw_avocado_raw',
    baseSlug: 'avocado',
    state: 'raw',
    priority: 'P0',
    nameHe: 'אבוקדו',
    nameEn: 'Avocado, raw',
    category: 'fruits',
    caloriesPer100g: 160,
    proteinPer100g: 2,
    fatPer100g: 14.66,
    carbsPer100g: 8.53,
    fiberPer100g: 6.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חצי אבוקדו', nameEn: 'Half avocado', unit: 'piece', grams: 68 },
      { nameHe: 'אבוקדו שלם', nameEn: 'Whole avocado', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 171705',
  },
  {
    id: 'raw_pineapple_raw',
    baseSlug: 'pineapple',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אננס',
    nameEn: 'Pineapple, raw',
    category: 'fruits',
    caloriesPer100g: 50,
    proteinPer100g: 0.54,
    fatPer100g: 0.12,
    carbsPer100g: 13.12,
    fiberPer100g: 1.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס קוביות', nameEn: 'Cup chunks', unit: 'cup', grams: 165 },
      { nameHe: 'פרוסה', nameEn: 'Slice', unit: 'piece', grams: 84 },
    ]),
    sourceComment: 'USDA SR Legacy 169124',
  },
  {
    id: 'raw_kiwi_raw',
    baseSlug: 'kiwi',
    state: 'raw',
    priority: 'P1',
    nameHe: 'קיווי',
    nameEn: 'Kiwifruit, raw',
    category: 'fruits',
    caloriesPer100g: 61,
    proteinPer100g: 1.14,
    fatPer100g: 0.52,
    carbsPer100g: 14.66,
    fiberPer100g: 3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'קיווי בינוני', nameEn: 'Medium kiwi', unit: 'piece', grams: 69 },
    ]),
    sourceComment: 'USDA SR Legacy 168153',
  },
  {
    id: 'raw_peach_raw',
    baseSlug: 'peach',
    state: 'raw',
    priority: 'P1',
    nameHe: 'אפרסק',
    nameEn: 'Peach, raw',
    category: 'fruits',
    caloriesPer100g: 39,
    proteinPer100g: 0.91,
    fatPer100g: 0.25,
    carbsPer100g: 9.54,
    fiberPer100g: 1.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'אפרסק בינוני', nameEn: 'Medium peach', unit: 'piece', grams: 150 },
    ]),
    sourceComment: 'USDA SR Legacy 169928',
  },
  {
    id: 'raw_nectarine_raw',
    baseSlug: 'nectarine',
    state: 'raw',
    priority: 'P2',
    nameHe: 'נקטרינה',
    nameEn: 'Nectarine, raw',
    category: 'fruits',
    caloriesPer100g: 44,
    proteinPer100g: 1.06,
    fatPer100g: 0.32,
    carbsPer100g: 10.55,
    fiberPer100g: 1.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'נקטרינה בינונית', nameEn: 'Medium nectarine', unit: 'piece', grams: 142 },
    ]),
    sourceComment: 'USDA SR Legacy 169914',
  },
  {
    id: 'raw_plum_raw',
    baseSlug: 'plum',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שזיף',
    nameEn: 'Plum, raw',
    category: 'fruits',
    caloriesPer100g: 46,
    proteinPer100g: 0.7,
    fatPer100g: 0.28,
    carbsPer100g: 11.42,
    fiberPer100g: 1.4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'שזיף אחד', nameEn: 'One plum', unit: 'piece', grams: 66 },
    ]),
    sourceComment: 'USDA SR Legacy 169949',
  },
  {
    id: 'raw_apricot_raw',
    baseSlug: 'apricot',
    state: 'raw',
    priority: 'P2',
    nameHe: 'משמש',
    nameEn: 'Apricot, raw',
    category: 'fruits',
    caloriesPer100g: 48,
    proteinPer100g: 1.4,
    fatPer100g: 0.39,
    carbsPer100g: 11.12,
    fiberPer100g: 2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'משמש אחד', nameEn: 'One apricot', unit: 'piece', grams: 35 },
    ]),
    sourceComment: 'USDA SR Legacy 171697',
  },
  {
    id: 'raw_cherry_raw',
    baseSlug: 'cherry',
    state: 'raw',
    priority: 'P2',
    nameHe: 'דובדבן',
    nameEn: 'Cherries, sweet, raw',
    category: 'fruits',
    caloriesPer100g: 63,
    proteinPer100g: 1.06,
    fatPer100g: 0.2,
    carbsPer100g: 16.01,
    fiberPer100g: 2.1,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס ללא גלעינים', nameEn: 'Cup pitted', unit: 'cup', grams: 154 },
      { nameHe: 'דובדבן אחד', nameEn: 'One cherry', unit: 'piece', grams: 8 },
    ]),
    sourceComment: 'USDA SR Legacy 171719',
  },
  {
    id: 'raw_fig_fresh_raw',
    baseSlug: 'fig_fresh',
    state: 'raw',
    priority: 'P2',
    nameHe: 'תאנה טרייה',
    nameEn: 'Fig, fresh, raw',
    category: 'fruits',
    caloriesPer100g: 74,
    proteinPer100g: 0.75,
    fatPer100g: 0.3,
    carbsPer100g: 19.18,
    fiberPer100g: 2.9,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'תאנה בינונית', nameEn: 'Medium fig', unit: 'piece', grams: 50 },
    ]),
    sourceComment: 'USDA SR Legacy 173021',
  },
  {
    id: 'raw_date_medjool_raw',
    baseSlug: 'date_medjool',
    state: 'raw',
    priority: 'P0',
    nameHe: "תמר מג'הול",
    nameEn: 'Dates, medjool',
    category: 'fruits',
    caloriesPer100g: 277,
    proteinPer100g: 1.81,
    fatPer100g: 0.15,
    carbsPer100g: 74.97,
    fiberPer100g: 6.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'תמר אחד', nameEn: 'One date', unit: 'piece', grams: 24 },
    ]),
    sourceComment: 'USDA SR Legacy 168191',
  },
  {
    id: 'raw_raisin_raw',
    baseSlug: 'raisin',
    state: 'raw',
    priority: 'P1',
    nameHe: 'צימוקים',
    nameEn: 'Raisins, seedless',
    category: 'fruits',
    caloriesPer100g: 301,
    proteinPer100g: 3.28,
    fatPer100g: 0.2,
    carbsPer100g: 80.02,
    fiberPer100g: 3.3,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 145 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 9 },
    ]),
    sourceComment: 'USDA SR Legacy 168164',
  },
  {
    id: 'raw_lemon_raw',
    baseSlug: 'lemon',
    state: 'raw',
    priority: 'P1',
    nameHe: 'לימון',
    nameEn: 'Lemon, raw',
    category: 'fruits',
    caloriesPer100g: 29,
    proteinPer100g: 1.1,
    fatPer100g: 0.3,
    carbsPer100g: 9.32,
    fiberPer100g: 2.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'לימון בינוני', nameEn: 'Medium lemon', unit: 'piece', grams: 84 },
      { nameHe: 'פלח', nameEn: 'Wedge', unit: 'piece', grams: 7 },
    ]),
    sourceComment: 'USDA SR Legacy 167746',
  },
  {
    id: 'raw_pomegranate_raw',
    baseSlug: 'pomegranate',
    state: 'raw',
    priority: 'P1',
    nameHe: 'רימון',
    nameEn: 'Pomegranate, raw',
    category: 'fruits',
    caloriesPer100g: 83,
    proteinPer100g: 1.67,
    fatPer100g: 1.17,
    carbsPer100g: 18.7,
    fiberPer100g: 4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'רימון שלם', nameEn: 'Whole fruit', unit: 'piece', grams: 282 },
      { nameHe: 'חצי כוס גרגרים', nameEn: 'Half cup arils', unit: 'cup', grams: 87 },
    ]),
    sourceComment: 'USDA SR Legacy 169134',
  },
  {
    id: 'raw_persimmon_raw',
    baseSlug: 'persimmon',
    state: 'raw',
    priority: 'P2',
    nameHe: 'אפרסמון',
    nameEn: 'Persimmon, raw',
    category: 'fruits',
    caloriesPer100g: 70,
    proteinPer100g: 0.58,
    fatPer100g: 0.19,
    carbsPer100g: 18.59,
    fiberPer100g: 3.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'אפרסמון בינוני', nameEn: 'Medium persimmon', unit: 'piece', grams: 168 },
    ]),
    sourceComment: 'USDA SR Legacy 169941',
  },
  // ─────────────────────────────────────────────────────────────────────
  // FATS / OILS / SPREADS (8) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_olive_oil_raw',
    baseSlug: 'olive_oil',
    state: 'raw',
    priority: 'P0',
    nameHe: 'שמן זית',
    nameEn: 'Olive oil',
    category: 'fats',
    caloriesPer100g: 884,
    proteinPer100g: 0,
    fatPer100g: 100,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 13.5 },
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 4.5 },
    ]),
    sourceComment: 'USDA SR Legacy 171413',
  },
  {
    id: 'raw_sunflower_oil_raw',
    baseSlug: 'sunflower_oil',
    state: 'raw',
    priority: 'P1',
    nameHe: 'שמן חמניות',
    nameEn: 'Sunflower oil',
    category: 'fats',
    caloriesPer100g: 884,
    proteinPer100g: 0,
    fatPer100g: 100,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 13.6 },
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 4.5 },
    ]),
    sourceComment: 'USDA SR Legacy 171025',
  },
  {
    id: 'raw_canola_oil_raw',
    baseSlug: 'canola_oil',
    state: 'raw',
    priority: 'P1',
    nameHe: 'שמן קנולה',
    nameEn: 'Canola oil',
    category: 'fats',
    caloriesPer100g: 884,
    proteinPer100g: 0,
    fatPer100g: 100,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 14 },
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 4.7 },
    ]),
    sourceComment: 'USDA SR Legacy 172336',
  },
  {
    id: 'raw_coconut_oil_raw',
    baseSlug: 'coconut_oil',
    state: 'raw',
    priority: 'P2',
    nameHe: 'שמן קוקוס',
    nameEn: 'Coconut oil',
    category: 'fats',
    caloriesPer100g: 892,
    proteinPer100g: 0,
    fatPer100g: 99.06,
    carbsPer100g: 0,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 13.6 }]),
    sourceComment: 'USDA SR Legacy 171412',
  },
  {
    id: 'raw_tahini_raw',
    baseSlug: 'tahini',
    state: 'raw',
    priority: 'P0',
    nameHe: 'טחינה גולמית',
    nameEn: 'Tahini (sesame butter), raw',
    category: 'fats',
    caloriesPer100g: 570,
    proteinPer100g: 17.81,
    fatPer100g: 48,
    carbsPer100g: 26.19,
    fiberPer100g: 9.3,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 15 }]),
    sourceComment: 'USDA SR Legacy 169410',
  },
  {
    id: 'raw_mayonnaise_raw',
    baseSlug: 'mayonnaise',
    state: 'raw',
    priority: 'P1',
    nameHe: 'מיונז',
    nameEn: 'Mayonnaise',
    category: 'fats',
    caloriesPer100g: 680,
    proteinPer100g: 0.96,
    fatPer100g: 74.85,
    carbsPer100g: 0.57,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 14 }]),
    sourceComment: 'USDA SR Legacy 171009',
  },
  {
    id: 'raw_peanut_butter_raw',
    baseSlug: 'peanut_butter',
    state: 'raw',
    priority: 'P0',
    nameHe: 'חמאת בוטנים',
    nameEn: 'Peanut butter, smooth',
    category: 'fats',
    caloriesPer100g: 598,
    proteinPer100g: 22.21,
    fatPer100g: 51.36,
    carbsPer100g: 22.31,
    fiberPer100g: 5,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 16 }]),
    sourceComment: 'USDA SR Legacy 172470',
  },
  {
    id: 'raw_almond_butter_raw',
    baseSlug: 'almond_butter',
    state: 'raw',
    priority: 'P2',
    nameHe: 'חמאת שקדים',
    nameEn: 'Almond butter, plain',
    category: 'fats',
    caloriesPer100g: 614,
    proteinPer100g: 20.96,
    fatPer100g: 55.5,
    carbsPer100g: 18.82,
    fiberPer100g: 10.3,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 16 }]),
    sourceComment: 'USDA SR Legacy 168588',
  },
  // ─────────────────────────────────────────────────────────────────────
  // NUTS & SEEDS (12) — USDA SR Legacy
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_walnut_raw',
    baseSlug: 'walnut',
    state: 'raw',
    priority: 'P0',
    nameHe: 'אגוזי מלך',
    nameEn: 'Walnuts, English',
    category: 'nuts',
    caloriesPer100g: 654,
    proteinPer100g: 15.23,
    fatPer100g: 65.21,
    carbsPer100g: 13.71,
    fiberPer100g: 6.7,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 },
      { nameHe: 'כוס קצוצים', nameEn: 'Cup chopped', unit: 'cup', grams: 117 },
    ]),
    sourceComment: 'USDA SR Legacy 170187',
  },
  {
    id: 'raw_almond_raw',
    baseSlug: 'almond',
    state: 'raw',
    priority: 'P0',
    nameHe: 'שקדים',
    nameEn: 'Almonds, raw',
    category: 'nuts',
    caloriesPer100g: 579,
    proteinPer100g: 21.15,
    fatPer100g: 49.93,
    carbsPer100g: 21.55,
    fiberPer100g: 12.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חופן (23 שקדים)', nameEn: 'Handful (23 almonds)', unit: 'handful', grams: 28 },
      { nameHe: 'כוס', nameEn: 'Cup whole', unit: 'cup', grams: 143 },
    ]),
    sourceComment: 'USDA SR Legacy 170567',
  },
  {
    id: 'raw_peanut_raw',
    baseSlug: 'peanut',
    state: 'raw',
    priority: 'P0',
    nameHe: 'בוטנים',
    nameEn: 'Peanuts, raw',
    category: 'nuts',
    caloriesPer100g: 567,
    proteinPer100g: 25.8,
    fatPer100g: 49.24,
    carbsPer100g: 16.13,
    fiberPer100g: 8.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 },
      { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 146 },
    ]),
    sourceComment: 'USDA SR Legacy 172430',
  },
  {
    id: 'raw_cashew_raw',
    baseSlug: 'cashew',
    state: 'raw',
    priority: 'P1',
    nameHe: 'קשיו',
    nameEn: 'Cashews, raw',
    category: 'nuts',
    caloriesPer100g: 553,
    proteinPer100g: 18.22,
    fatPer100g: 43.85,
    carbsPer100g: 30.19,
    fiberPer100g: 3.3,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 170162',
  },
  {
    id: 'raw_pistachio_raw',
    baseSlug: 'pistachio',
    state: 'raw',
    priority: 'P1',
    nameHe: 'פיסטוקים',
    nameEn: 'Pistachios, raw',
    category: 'nuts',
    caloriesPer100g: 560,
    proteinPer100g: 20.16,
    fatPer100g: 45.32,
    carbsPer100g: 27.17,
    fiberPer100g: 10.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'חופן (49 גרגרים)', nameEn: 'Handful (49 kernels)', unit: 'handful', grams: 28 },
    ]),
    sourceComment: 'USDA SR Legacy 170184',
  },
  {
    id: 'raw_pecan_raw',
    baseSlug: 'pecan',
    state: 'raw',
    priority: 'P2',
    nameHe: 'פקאן',
    nameEn: 'Pecans, raw',
    category: 'nuts',
    caloriesPer100g: 691,
    proteinPer100g: 9.17,
    fatPer100g: 71.97,
    carbsPer100g: 13.86,
    fiberPer100g: 9.6,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 170182',
  },
  {
    id: 'raw_hazelnut_raw',
    baseSlug: 'hazelnut',
    state: 'raw',
    priority: 'P2',
    nameHe: 'אגוזי לוז',
    nameEn: 'Hazelnuts, raw',
    category: 'nuts',
    caloriesPer100g: 628,
    proteinPer100g: 14.95,
    fatPer100g: 60.75,
    carbsPer100g: 16.7,
    fiberPer100g: 9.7,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 170581',
  },
  {
    id: 'raw_brazil_nut_raw',
    baseSlug: 'brazil_nut',
    state: 'raw',
    priority: 'P2',
    nameHe: 'אגוזי ברזיל',
    nameEn: 'Brazil nuts, dried',
    category: 'nuts',
    caloriesPer100g: 659,
    proteinPer100g: 14.32,
    fatPer100g: 67.1,
    carbsPer100g: 11.74,
    fiberPer100g: 7.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'אגוז אחד', nameEn: 'One nut', unit: 'piece', grams: 5 },
      { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 },
    ]),
    sourceComment: 'USDA SR Legacy 170569',
  },
  {
    id: 'raw_sunflower_seeds_raw',
    baseSlug: 'sunflower_seeds',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גרעיני חמניות',
    nameEn: 'Sunflower seed kernels, dried',
    category: 'nuts',
    caloriesPer100g: 584,
    proteinPer100g: 20.78,
    fatPer100g: 51.46,
    carbsPer100g: 20,
    fiberPer100g: 8.6,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 9 },
      { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 },
    ]),
    sourceComment: 'USDA SR Legacy 170562',
  },
  {
    id: 'raw_pumpkin_seeds_raw',
    baseSlug: 'pumpkin_seeds',
    state: 'raw',
    priority: 'P1',
    nameHe: 'גרעיני דלעת',
    nameEn: 'Pumpkin seed kernels, dried',
    category: 'nuts',
    caloriesPer100g: 559,
    proteinPer100g: 30.23,
    fatPer100g: 49.05,
    carbsPer100g: 10.71,
    fiberPer100g: 6,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'חופן', nameEn: 'Handful', unit: 'handful', grams: 28 }]),
    sourceComment: 'USDA SR Legacy 170556',
  },
  {
    id: 'raw_chia_seeds_raw',
    baseSlug: 'chia_seeds',
    state: 'raw',
    priority: 'P2',
    nameHe: "זרעי צ'יה",
    nameEn: 'Chia seeds, dried',
    category: 'nuts',
    caloriesPer100g: 486,
    proteinPer100g: 16.54,
    fatPer100g: 30.74,
    carbsPer100g: 42.12,
    fiberPer100g: 34.4,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 12 }]),
    sourceComment: 'USDA SR Legacy 170554',
  },
  {
    id: 'raw_flax_seeds_raw',
    baseSlug: 'flax_seeds',
    state: 'raw',
    priority: 'P2',
    nameHe: 'זרעי פשתן',
    nameEn: 'Flaxseeds, dried',
    category: 'nuts',
    caloriesPer100g: 534,
    proteinPer100g: 18.29,
    fatPer100g: 42.16,
    carbsPer100g: 28.88,
    fiberPer100g: 27.3,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 10 }]),
    sourceComment: 'USDA SR Legacy 169414',
  },
  // ─────────────────────────────────────────────────────────────────────
  // CONDIMENTS & SWEETENERS (9) — USDA SR Legacy
  // Note: salt (fdc 173468) omitted — 0 kcal fails schema positive() rule.
  // ─────────────────────────────────────────────────────────────────────
  {
    id: 'raw_sugar_white_raw',
    baseSlug: 'sugar_white',
    state: 'raw',
    priority: 'P0',
    nameHe: 'סוכר לבן',
    nameEn: 'Sugar, granulated',
    category: 'condiments',
    caloriesPer100g: 387,
    proteinPer100g: 0,
    fatPer100g: 0,
    carbsPer100g: 99.98,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 4.2 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 12.5 },
    ]),
    sourceComment: 'USDA SR Legacy 169655',
  },
  {
    id: 'raw_brown_sugar_raw',
    baseSlug: 'brown_sugar',
    state: 'raw',
    priority: 'P2',
    nameHe: 'סוכר חום',
    nameEn: 'Sugar, brown',
    category: 'condiments',
    caloriesPer100g: 380,
    proteinPer100g: 0.12,
    fatPer100g: 0,
    carbsPer100g: 98.09,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 4.6 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 13.8 },
    ]),
    sourceComment: 'USDA SR Legacy 168833',
  },
  {
    id: 'raw_honey_raw',
    baseSlug: 'honey',
    state: 'raw',
    priority: 'P0',
    nameHe: 'דבש',
    nameEn: 'Honey',
    category: 'condiments',
    caloriesPer100g: 304,
    proteinPer100g: 0.3,
    fatPer100g: 0,
    carbsPer100g: 82.4,
    fiberPer100g: 0.2,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 21 },
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 7 },
    ]),
    sourceComment: 'USDA SR Legacy 169640',
  },
  {
    id: 'raw_silan_date_syrup_raw',
    baseSlug: 'silan_date_syrup',
    state: 'raw',
    priority: 'P1',
    nameHe: 'סילאן (סירופ תמרים)',
    nameEn: 'Silan (date syrup)',
    category: 'condiments',
    caloriesPer100g: 234,
    proteinPer100g: 0,
    fatPer100g: 0,
    carbsPer100g: 61.47,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 20 }]),
    sourceComment: 'USDA SR Legacy 169578 (pancake syrup proxy)',
  },
  {
    id: 'raw_vinegar_raw',
    baseSlug: 'vinegar',
    state: 'raw',
    priority: 'P2',
    nameHe: 'חומץ',
    nameEn: 'Vinegar, distilled',
    category: 'condiments',
    caloriesPer100g: 18,
    proteinPer100g: 0,
    fatPer100g: 0,
    carbsPer100g: 0.04,
    fiberPer100g: 0,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 15 }]),
    sourceComment: 'USDA SR Legacy 172237',
  },
  {
    id: 'raw_soy_sauce_raw',
    baseSlug: 'soy_sauce',
    state: 'raw',
    priority: 'P1',
    nameHe: 'רוטב סויה',
    nameEn: 'Soy sauce (shoyu)',
    category: 'condiments',
    caloriesPer100g: 53,
    proteinPer100g: 8.14,
    fatPer100g: 0.57,
    carbsPer100g: 4.93,
    fiberPer100g: 0.8,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 16 },
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 5 },
    ]),
    sourceComment: 'USDA SR Legacy 174277',
  },
  {
    id: 'raw_tomato_sauce_raw',
    baseSlug: 'tomato_sauce',
    state: 'raw',
    priority: 'P1',
    nameHe: 'רסק עגבניות',
    nameEn: 'Tomato sauce, canned',
    category: 'condiments',
    caloriesPer100g: 24,
    proteinPer100g: 1.2,
    fatPer100g: 0.3,
    carbsPer100g: 5.31,
    fiberPer100g: 1.5,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כוס', nameEn: 'Cup', unit: 'cup', grams: 245 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 15 },
    ]),
    sourceComment: 'USDA SR Legacy 170054',
  },
  {
    id: 'raw_ketchup_raw',
    baseSlug: 'ketchup',
    state: 'raw',
    priority: 'P1',
    nameHe: 'קטשופ',
    nameEn: 'Ketchup',
    category: 'condiments',
    caloriesPer100g: 101,
    proteinPer100g: 1.04,
    fatPer100g: 0.1,
    carbsPer100g: 27.4,
    fiberPer100g: 0.3,
    isUserCreated: false,
    servingSizesJson: j([g100, { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 17 }]),
    sourceComment: 'USDA SR Legacy 168556',
  },
  {
    id: 'raw_mustard_raw',
    baseSlug: 'mustard',
    state: 'raw',
    priority: 'P2',
    nameHe: 'חרדל',
    nameEn: 'Mustard, prepared yellow',
    category: 'condiments',
    caloriesPer100g: 60,
    proteinPer100g: 3.74,
    fatPer100g: 3.34,
    carbsPer100g: 5.83,
    fiberPer100g: 4,
    isUserCreated: false,
    servingSizesJson: j([
      g100,
      { nameHe: 'כפית', nameEn: 'Teaspoon', unit: 'tsp', grams: 5 },
      { nameHe: 'כף', nameEn: 'Tablespoon', unit: 'tbsp', grams: 15 },
    ]),
    sourceComment: 'USDA SR Legacy 172234',
  },
]
